// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __conv_layer1_conv_cud_H__
#define __conv_layer1_conv_cud_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct conv_layer1_conv_cud_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 8;
  static const unsigned AddressRange = 128;
  static const unsigned AddressWidth = 7;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(conv_layer1_conv_cud_ram) {
        ram[0] = "0b01100000";
        ram[1] = "0b00011101";
        ram[2] = "0b00011111";
        ram[3] = "0b01001100";
        ram[4] = "0b00001011";
        ram[5] = "0b11110000";
        ram[6] = "0b10000001";
        ram[7] = "0b00101110";
        ram[8] = "0b11011110";
        ram[9] = "0b01000110";
        ram[10] = "0b11110001";
        ram[11] = "0b00011011";
        ram[12] = "0b10100111";
        ram[13] = "0b00111001";
        ram[14] = "0b11101011";
        ram[15] = "0b11100111";
        ram[16] = "0b11010100";
        ram[17] = "0b01110100";
        ram[18] = "0b01100001";
        ram[19] = "0b10110110";
        ram[20] = "0b10001100";
        ram[21] = "0b01000100";
        ram[22] = "0b10001110";
        ram[23] = "0b11101110";
        ram[24] = "0b00011001";
        ram[25] = "0b11111010";
        ram[26] = "0b10100110";
        ram[27] = "0b10000001";
        ram[28] = "0b11001011";
        ram[29] = "0b10101000";
        ram[30] = "0b11110000";
        ram[31] = "0b01100100";
        ram[32] = "0b11110010";
        ram[33] = "0b01100101";
        ram[34] = "0b01101010";
        ram[35] = "0b11001100";
        ram[36] = "0b00101011";
        ram[37] = "0b10100011";
        ram[38] = "0b01000111";
        ram[39] = "0b11101101";
        ram[40] = "0b01001100";
        ram[41] = "0b00000001";
        ram[42] = "0b01011100";
        ram[43] = "0b00010001";
        ram[44] = "0b11110100";
        ram[45] = "0b10000001";
        ram[46] = "0b01000110";
        ram[47] = "0b01001010";
        ram[48] = "0b00001000";
        ram[49] = "0b11000100";
        ram[50] = "0b00000000";
        ram[51] = "0b00001010";
        ram[52] = "0b10100101";
        ram[53] = "0b10111111";
        ram[54] = "0b01011000";
        ram[55] = "0b01001101";
        ram[56] = "0b11110010";
        ram[57] = "0b10000001";
        ram[58] = "0b10001110";
        ram[59] = "0b11110111";
        ram[60] = "0b01000100";
        ram[61] = "0b00100101";
        ram[62] = "0b11100010";
        ram[63] = "0b11101100";
        ram[64] = "0b00101010";
        ram[65] = "0b00111000";
        ram[66] = "0b00111011";
        ram[67] = "0b10100111";
        ram[68] = "0b00010000";
        ram[69] = "0b11100100";
        ram[70] = "0b11100110";
        ram[71] = "0b11011001";
        ram[72] = "0b00000000";
        ram[73] = "0b11110011";
        ram[74] = "0b11111101";
        ram[75] = "0b10000001";
        ram[76] = "0b00011110";
        ram[77] = "0b00000001";
        ram[78] = "0b11011101";
        ram[79] = "0b10100101";
        ram[80] = "0b01001111";
        ram[81] = "0b11101111";
        ram[82] = "0b10011100";
        ram[83] = "0b11111011";
        ram[84] = "0b11010010";
        ram[85] = "0b01000001";
        ram[86] = "0b10001110";
        ram[87] = "0b00011110";
        ram[88] = "0b10110110";
        ram[89] = "0b10000001";
        ram[90] = "0b10101001";
        ram[91] = "0b11010111";
        ram[92] = "0b11110100";
        ram[93] = "0b01010111";
        ram[94] = "0b11001001";
        ram[95] = "0b11100110";
        ram[96] = "0b10110101";
        ram[97] = "0b00000111";
        ram[98] = "0b00101100";
        ram[99] = "0b10000001";
        ram[100] = "0b01010011";
        ram[101] = "0b00100010";
        ram[102] = "0b00011100";
        ram[103] = "0b10110101";
        ram[104] = "0b11101100";
        ram[105] = "0b00000001";
        ram[106] = "0b10010111";
        ram[107] = "0b10010111";
        ram[108] = "0b11101110";
        ram[109] = "0b01000110";
        ram[110] = "0b00101111";
        ram[111] = "0b10101101";
        ram[112] = "0b00110010";
        ram[113] = "0b00011011";
        ram[114] = "0b01000010";
        ram[115] = "0b00011000";
        ram[116] = "0b10011011";
        ram[117] = "0b00100111";
        ram[118] = "0b01011101";
        ram[119] = "0b01010010";
        ram[120] = "0b11111101";
        ram[121] = "0b00111110";
        ram[122] = "0b10000001";
        ram[123] = "0b00011100";
        ram[124] = "0b01000100";
        ram[125] = "0b00010110";
        ram[126] = "0b00000101";
        ram[127] = "0b01001111";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(conv_layer1_conv_cud) {


static const unsigned DataWidth = 8;
static const unsigned AddressRange = 128;
static const unsigned AddressWidth = 7;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


conv_layer1_conv_cud_ram* meminst;


SC_CTOR(conv_layer1_conv_cud) {
meminst = new conv_layer1_conv_cud_ram("conv_layer1_conv_cud_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~conv_layer1_conv_cud() {
    delete meminst;
}


};//endmodule
#endif
