// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __conv_layer2_conv_bXr_H__
#define __conv_layer2_conv_bXr_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct conv_layer2_conv_bXr_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 11;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(conv_layer2_conv_bXr_ram) {
        ram[0] = "0b11101000100";
        ram[1] = "0b11001000101";
        ram[2] = "0b11110101001";
        ram[3] = "0b00000011100";
        ram[4] = "0b11100011101";
        ram[5] = "0b11110111000";
        ram[6] = "0b11100111010";
        ram[7] = "0b11001001011";
        ram[8] = "0b11011011010";
        ram[9] = "0b11110001100";
        ram[10] = "0b11000010010";
        ram[11] = "0b10111111100";
        ram[12] = "0b11111101111";
        ram[13] = "0b11111000101";
        ram[14] = "0b11011000111";
        ram[15] = "0b11110111011";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(conv_layer2_conv_bXr) {


static const unsigned DataWidth = 11;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


conv_layer2_conv_bXr_ram* meminst;


SC_CTOR(conv_layer2_conv_bXr) {
meminst = new conv_layer2_conv_bXr_ram("conv_layer2_conv_bXr_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~conv_layer2_conv_bXr() {
    delete meminst;
}


};//endmodule
#endif
