// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __conv_layer2_scalebYs_H__
#define __conv_layer2_scalebYs_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct conv_layer2_scalebYs_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 20;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(conv_layer2_scalebYs_ram) {
        ram[0] = "0b10010011011100100100";
        ram[1] = "0b10100001111000100101";
        ram[2] = "0b10100101001111111110";
        ram[3] = "0b10000111011010110010";
        ram[4] = "0b10001000010101111100";
        ram[5] = "0b10110001000100001000";
        ram[6] = "0b10010011111001011111";
        ram[7] = "0b10010110111000100111";
        ram[8] = "0b10001100011101100001";
        ram[9] = "0b10100010110110101111";
        ram[10] = "0b11011010110111000111";
        ram[11] = "0b10010111011110001010";
        ram[12] = "0b10100000101011110011";
        ram[13] = "0b10100010001000111000";
        ram[14] = "0b10011011100101011010";
        ram[15] = "0b10010000100010011100";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(conv_layer2_scalebYs) {


static const unsigned DataWidth = 20;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


conv_layer2_scalebYs_ram* meminst;


SC_CTOR(conv_layer2_scalebYs) {
meminst = new conv_layer2_scalebYs_ram("conv_layer2_scalebYs_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~conv_layer2_scalebYs() {
    delete meminst;
}


};//endmodule
#endif
