// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "fc_layer1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic fc_layer1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic fc_layer1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<12> fc_layer1::ap_ST_fsm_state1 = "1";
const sc_lv<12> fc_layer1::ap_ST_fsm_state2 = "10";
const sc_lv<12> fc_layer1::ap_ST_fsm_state3 = "100";
const sc_lv<12> fc_layer1::ap_ST_fsm_state4 = "1000";
const sc_lv<12> fc_layer1::ap_ST_fsm_state5 = "10000";
const sc_lv<12> fc_layer1::ap_ST_fsm_state6 = "100000";
const sc_lv<12> fc_layer1::ap_ST_fsm_state7 = "1000000";
const sc_lv<12> fc_layer1::ap_ST_fsm_state8 = "10000000";
const sc_lv<12> fc_layer1::ap_ST_fsm_state9 = "100000000";
const sc_lv<12> fc_layer1::ap_ST_fsm_state10 = "1000000000";
const sc_lv<12> fc_layer1::ap_ST_fsm_state11 = "10000000000";
const sc_lv<12> fc_layer1::ap_ST_fsm_state12 = "100000000000";
const sc_lv<32> fc_layer1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> fc_layer1::ap_const_lv32_B = "1011";
const sc_lv<32> fc_layer1::ap_const_lv32_3 = "11";
const sc_lv<1> fc_layer1::ap_const_lv1_0 = "0";
const sc_lv<32> fc_layer1::ap_const_lv32_1 = "1";
const sc_lv<32> fc_layer1::ap_const_lv32_4 = "100";
const sc_lv<1> fc_layer1::ap_const_lv1_1 = "1";
const sc_lv<32> fc_layer1::ap_const_lv32_5 = "101";
const sc_lv<32> fc_layer1::ap_const_lv32_6 = "110";
const sc_lv<32> fc_layer1::ap_const_lv32_8 = "1000";
const sc_lv<32> fc_layer1::ap_const_lv32_9 = "1001";
const sc_lv<32> fc_layer1::ap_const_lv32_A = "1010";
const sc_lv<7> fc_layer1::ap_const_lv7_0 = "0000000";
const sc_lv<32> fc_layer1::ap_const_lv32_2 = "10";
const sc_lv<10> fc_layer1::ap_const_lv10_1 = "1";
const sc_lv<32> fc_layer1::ap_const_lv32_7 = "111";
const sc_lv<64> fc_layer1::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<24> fc_layer1::ap_const_lv24_0 = "000000000000000000000000";
const sc_lv<9> fc_layer1::ap_const_lv9_2 = "10";
const sc_lv<7> fc_layer1::ap_const_lv7_78 = "1111000";
const sc_lv<7> fc_layer1::ap_const_lv7_1 = "1";
const sc_lv<9> fc_layer1::ap_const_lv9_0 = "000000000";
const sc_lv<6> fc_layer1::ap_const_lv6_0 = "000000";
const sc_lv<10> fc_layer1::ap_const_lv10_240 = "1001000000";
const sc_lv<7> fc_layer1::ap_const_lv7_2 = "10";
const sc_lv<7> fc_layer1::ap_const_lv7_3 = "11";
const sc_lv<7> fc_layer1::ap_const_lv7_4 = "100";
const sc_lv<44> fc_layer1::ap_const_lv44_8169D = "10000001011010011101";
const sc_lv<32> fc_layer1::ap_const_lv32_2B = "101011";
const sc_lv<32> fc_layer1::ap_const_lv32_1C = "11100";
const sc_lv<32> fc_layer1::ap_const_lv32_1B = "11011";
const sc_lv<27> fc_layer1::ap_const_lv27_0 = "000000000000000000000000000";
const sc_lv<32> fc_layer1::ap_const_lv32_10 = "10000";
const sc_lv<17> fc_layer1::ap_const_lv17_0 = "00000000000000000";
const sc_lv<24> fc_layer1::ap_const_lv24_FFFFFE = "111111111111111111111110";
const sc_lv<32> fc_layer1::ap_const_lv32_17 = "10111";
const sc_lv<8> fc_layer1::ap_const_lv8_FE = "11111110";
const sc_lv<16> fc_layer1::ap_const_lv16_0 = "0000000000000000";
const sc_lv<16> fc_layer1::ap_const_lv16_FFFF = "1111111111111111";
const sc_lv<8> fc_layer1::ap_const_lv8_7F = "1111111";
const sc_lv<8> fc_layer1::ap_const_lv8_80 = "10000000";
const sc_lv<31> fc_layer1::ap_const_lv31_816A0 = "10000001011010100000";
const bool fc_layer1::ap_const_boolean_1 = true;

fc_layer1::fc_layer1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    fc_layer1_weights_V_U = new fc_layer1_fc_layeb7t("fc_layer1_weights_V_U");
    fc_layer1_weights_V_U->clk(ap_clk);
    fc_layer1_weights_V_U->reset(ap_rst);
    fc_layer1_weights_V_U->address0(fc_layer1_weights_V_address0);
    fc_layer1_weights_V_U->ce0(fc_layer1_weights_V_ce0);
    fc_layer1_weights_V_U->q0(fc_layer1_weights_V_q0);
    fc_layer1_weights_V_U->address1(fc_layer1_weights_V_address1);
    fc_layer1_weights_V_U->ce1(fc_layer1_weights_V_ce1);
    fc_layer1_weights_V_U->q1(fc_layer1_weights_V_q1);
    fc_layer1_bias_V_U = new fc_layer1_fc_layeb8t("fc_layer1_bias_V_U");
    fc_layer1_bias_V_U->clk(ap_clk);
    fc_layer1_bias_V_U->reset(ap_rst);
    fc_layer1_bias_V_U->address0(fc_layer1_bias_V_address0);
    fc_layer1_bias_V_U->ce0(fc_layer1_bias_V_ce0);
    fc_layer1_bias_V_U->q0(fc_layer1_bias_V_q0);
    output_V_U = new fc_layer1_output_V("output_V_U");
    output_V_U->clk(ap_clk);
    output_V_U->reset(ap_rst);
    output_V_U->address0(output_V_address0);
    output_V_U->ce0(output_V_ce0);
    output_V_U->we0(output_V_we0);
    output_V_U->d0(output_V_d0);
    output_V_U->q0(output_V_q0);
    output_V_U->address1(output_V_address1);
    output_V_U->ce1(output_V_ce1);
    output_V_U->we1(output_V_we1);
    output_V_U->d1(output_V_d1);
    output_V_U->q1(output_V_q1);
    nnet_mac_muladd_8b9t_U56 = new nnet_mac_muladd_8b9t<1,1,8,9,24,24>("nnet_mac_muladd_8b9t_U56");
    nnet_mac_muladd_8b9t_U56->din0(fc_layer1_weights_V_q0);
    nnet_mac_muladd_8b9t_U56->din1(grp_fu_914_p1);
    nnet_mac_muladd_8b9t_U56->din2(output_V_q0);
    nnet_mac_muladd_8b9t_U56->dout(grp_fu_914_p3);
    nnet_mac_muladd_8b9t_U57 = new nnet_mac_muladd_8b9t<1,1,8,9,24,24>("nnet_mac_muladd_8b9t_U57");
    nnet_mac_muladd_8b9t_U57->din0(fc_layer1_weights_V_q1);
    nnet_mac_muladd_8b9t_U57->din1(grp_fu_921_p1);
    nnet_mac_muladd_8b9t_U57->din2(output_V_q1);
    nnet_mac_muladd_8b9t_U57->dout(grp_fu_921_p3);
    nnet_mac_muladd_8b9t_U58 = new nnet_mac_muladd_8b9t<1,1,8,9,24,24>("nnet_mac_muladd_8b9t_U58");
    nnet_mac_muladd_8b9t_U58->din0(fc_layer1_weights_V_q0);
    nnet_mac_muladd_8b9t_U58->din1(grp_fu_928_p1);
    nnet_mac_muladd_8b9t_U58->din2(output_V_q1);
    nnet_mac_muladd_8b9t_U58->dout(grp_fu_928_p3);
    nnet_mac_muladd_8b9t_U59 = new nnet_mac_muladd_8b9t<1,1,8,9,24,24>("nnet_mac_muladd_8b9t_U59");
    nnet_mac_muladd_8b9t_U59->din0(fc_layer1_weights_V_q1);
    nnet_mac_muladd_8b9t_U59->din1(grp_fu_935_p1);
    nnet_mac_muladd_8b9t_U59->din2(output_V_q0);
    nnet_mac_muladd_8b9t_U59->dout(grp_fu_935_p3);
    nnet_mac_muladd_3cau_U60 = new nnet_mac_muladd_3cau<1,1,31,10,44,44>("nnet_mac_muladd_3cau_U60");
    nnet_mac_muladd_3cau_U60->din0(ap_var_for_const0);
    nnet_mac_muladd_3cau_U60->din1(f_op_V_3_reg_1088);
    nnet_mac_muladd_3cau_U60->din2(p_Val2_s_reg_1083);
    nnet_mac_muladd_3cau_U60->dout(grp_fu_942_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( in_V_V_empty_n );

    SC_METHOD(thread_ap_block_state4);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( exitcond6_fu_411_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( exitcond_fu_667_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( exitcond_fu_667_p2 );

    SC_METHOD(thread_brmerge39_i_i_fu_860_p2);
    sensitive << ( p_not38_i_i_fu_855_p2 );
    sensitive << ( newsignbit_0_not_i_i_fu_849_p2 );

    SC_METHOD(thread_brmerge_fu_883_p2);
    sensitive << ( overflow_fu_843_p2 );
    sensitive << ( underflow_not_fu_877_p2 );

    SC_METHOD(thread_brmerge_i_i_fu_832_p2);
    sensitive << ( newsignbit_fu_819_p3 );
    sensitive << ( p_not_i_i_fu_827_p2 );

    SC_METHOD(thread_brmerge_i_i_i_fu_871_p2);
    sensitive << ( underflow_fu_866_p2 );
    sensitive << ( overflow_fu_843_p2 );

    SC_METHOD(thread_exitcond2_fu_435_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i1_reg_308 );

    SC_METHOD(thread_exitcond5_fu_345_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_284 );

    SC_METHOD(thread_exitcond6_fu_411_p2);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond6_fu_411_p2 );
    sensitive << ( j_reg_296 );

    SC_METHOD(thread_exitcond_fu_667_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( i2_reg_320 );

    SC_METHOD(thread_fc_layer1_bias_V_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_5_fu_679_p1 );

    SC_METHOD(thread_fc_layer1_bias_V_ce0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_fc_layer1_weights_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_40_cast_fu_387_p1 );
    sensitive << ( tmp_44_cast_fu_481_p1 );
    sensitive << ( tmp_52_cast_fu_597_p1 );

    SC_METHOD(thread_fc_layer1_weights_V_address1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_48_cast_fu_532_p1 );
    sensitive << ( tmp_56_cast_fu_648_p1 );

    SC_METHOD(thread_fc_layer1_weights_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_fc_layer1_weights_V_ce1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_grp_fu_914_p1);
    sensitive << ( p_1_cast_reg_982 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_grp_fu_921_p1);
    sensitive << ( p_1_cast_reg_982 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_grp_fu_928_p1);
    sensitive << ( p_1_cast_reg_982 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_grp_fu_935_p1);
    sensitive << ( p_1_cast_reg_982 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_i_10_1_fu_551_p2);
    sensitive << ( i1_reg_308 );

    SC_METHOD(thread_i_10_2_fu_602_p2);
    sensitive << ( i1_reg_308 );

    SC_METHOD(thread_i_10_3_fu_653_p2);
    sensitive << ( i1_reg_308 );

    SC_METHOD(thread_i_10_s_fu_486_p2);
    sensitive << ( i1_reg_308 );

    SC_METHOD(thread_i_6_fu_351_p2);
    sensitive << ( i_reg_284 );

    SC_METHOD(thread_i_7_fu_673_p2);
    sensitive << ( i2_reg_320 );

    SC_METHOD(thread_in_V_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond6_fu_411_p2 );

    SC_METHOD(thread_in_V_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond6_fu_411_p2 );

    SC_METHOD(thread_j_3_fu_537_p2);
    sensitive << ( j_reg_296 );

    SC_METHOD(thread_lhs_V_3_fu_417_p1);
    sensitive << ( in_V_V_dout );

    SC_METHOD(thread_lhs_V_fu_331_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_V_V_dout );

    SC_METHOD(thread_lhs_V_fu_331_p1);
    sensitive << ( lhs_V_fu_331_p0 );

    SC_METHOD(thread_newsignbit_0_not_i_i_fu_849_p2);
    sensitive << ( newsignbit_fu_819_p3 );

    SC_METHOD(thread_newsignbit_fu_819_p3);
    sensitive << ( p_Val2_15_fu_814_p2 );

    SC_METHOD(thread_not_s_i_i3_fu_734_p2);
    sensitive << ( tmp_57_fu_698_p3 );

    SC_METHOD(thread_out_V_V_blk_n);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_out_V_V_din);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( brmerge_fu_883_p2 );
    sensitive << ( p_Val2_35_mux_fu_889_p3 );
    sensitive << ( p_Val2_s_525_fu_897_p3 );

    SC_METHOD(thread_out_V_V_write);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_output_V_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( output_V_addr_12_reg_1009 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( output_V_addr_14_reg_1045 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_s_fu_392_p1 );
    sensitive << ( tmp_8_fu_441_p1 );
    sensitive << ( tmp_103_3_fu_608_p1 );

    SC_METHOD(thread_output_V_address1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( output_V_addr_11_reg_998 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( output_V_addr_13_reg_1035 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_103_1_fu_492_p1 );
    sensitive << ( tmp_103_2_fu_557_p1 );
    sensitive << ( tmp_5_fu_679_p1 );

    SC_METHOD(thread_output_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_output_V_ce1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_output_V_d0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_104_1_reg_1025 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_104_3_reg_1060 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( p_9_cast_fu_406_p1 );

    SC_METHOD(thread_output_V_d1);
    sensitive << ( tmp_9_reg_1020 );
    sensitive << ( tmp_104_2_reg_1055 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_output_V_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_output_V_we1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_overflow_fu_843_p2);
    sensitive << ( brmerge_i_i_fu_832_p2 );
    sensitive << ( tmp_7_fu_838_p2 );

    SC_METHOD(thread_p_1_cast_fu_431_p1);
    sensitive << ( r_V_5_fu_421_p2 );

    SC_METHOD(thread_p_9_cast_fu_406_p1);
    sensitive << ( p_9_fu_401_p2 );

    SC_METHOD(thread_p_9_fu_401_p0);
    sensitive << ( fc_layer1_weights_V_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_p_9_fu_401_p1);
    sensitive << ( read_temp_V_cast_reg_953 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_p_9_fu_401_p2);
    sensitive << ( p_9_fu_401_p0 );
    sensitive << ( p_9_fu_401_p1 );

    SC_METHOD(thread_p_Val2_13_fu_756_p2);
    sensitive << ( tmp_16_cast_fu_752_p1 );
    sensitive << ( p_Val2_15_cast_fu_714_p1 );

    SC_METHOD(thread_p_Val2_15_cast_fu_714_p1);
    sensitive << ( tmp_13_fu_705_p4 );

    SC_METHOD(thread_p_Val2_15_fu_814_p2);
    sensitive << ( tmp_61_reg_1093 );

    SC_METHOD(thread_p_Val2_35_mux_fu_889_p3);
    sensitive << ( p_Val2_15_fu_814_p2 );
    sensitive << ( brmerge_i_i_i_fu_871_p2 );

    SC_METHOD(thread_p_Val2_s_525_fu_897_p3);
    sensitive << ( p_Val2_15_fu_814_p2 );
    sensitive << ( underflow_fu_866_p2 );

    SC_METHOD(thread_p_Val2_s_fu_689_p1);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( output_V_q1 );

    SC_METHOD(thread_p_Val2_s_fu_689_p2);
    sensitive << ( p_Val2_s_fu_689_p1 );

    SC_METHOD(thread_p_a_V_i_cast1_fu_778_p1);
    sensitive << ( p_a_V_i_fu_770_p3 );

    SC_METHOD(thread_p_a_V_i_cast_fu_782_p1);
    sensitive << ( p_a_V_i_cast1_fu_778_p1 );

    SC_METHOD(thread_p_a_V_i_fu_770_p3);
    sensitive << ( p_Val2_13_fu_756_p2 );
    sensitive << ( tmp_60_fu_762_p3 );

    SC_METHOD(thread_p_not38_i_i_fu_855_p2);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_14_reg_1104 );

    SC_METHOD(thread_p_not_i_i_fu_827_p2);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_14_reg_1104 );

    SC_METHOD(thread_p_shl1_cast_fu_377_p1);
    sensitive << ( tmp_38_fu_369_p3 );

    SC_METHOD(thread_p_shl2_cast_fu_621_p1);
    sensitive << ( tmp_52_fu_613_p3 );

    SC_METHOD(thread_p_shl3_cast_fu_633_p1);
    sensitive << ( tmp_53_fu_625_p3 );

    SC_METHOD(thread_p_shl4_cast_fu_570_p1);
    sensitive << ( tmp_48_fu_562_p3 );

    SC_METHOD(thread_p_shl5_cast_fu_582_p1);
    sensitive << ( tmp_49_fu_574_p3 );

    SC_METHOD(thread_p_shl6_cast_fu_505_p1);
    sensitive << ( tmp_44_fu_497_p3 );

    SC_METHOD(thread_p_shl7_cast_fu_517_p1);
    sensitive << ( tmp_45_fu_509_p3 );

    SC_METHOD(thread_p_shl8_cast_fu_454_p1);
    sensitive << ( tmp_40_fu_446_p3 );

    SC_METHOD(thread_p_shl9_cast_fu_466_p1);
    sensitive << ( tmp_41_fu_458_p3 );

    SC_METHOD(thread_p_shl_cast_fu_365_p1);
    sensitive << ( tmp_37_fu_357_p3 );

    SC_METHOD(thread_qb_assign_3_fu_746_p2);
    sensitive << ( r_i_i3_fu_740_p2 );
    sensitive << ( qbit_fu_718_p3 );

    SC_METHOD(thread_qbit_fu_718_p3);
    sensitive << ( grp_fu_942_p3 );

    SC_METHOD(thread_r_V_5_fu_421_p2);
    sensitive << ( lhs_V_3_fu_417_p1 );

    SC_METHOD(thread_r_V_7_fu_790_p2);
    sensitive << ( p_a_V_i_cast_fu_782_p1 );

    SC_METHOD(thread_r_V_fu_335_p2);
    sensitive << ( lhs_V_fu_331_p1 );

    SC_METHOD(thread_r_fu_728_p2);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( tmp_59_fu_725_p1 );

    SC_METHOD(thread_r_i_i3_fu_740_p2);
    sensitive << ( r_fu_728_p2 );
    sensitive << ( not_s_i_i3_fu_734_p2 );

    SC_METHOD(thread_read_temp_V_cast_fu_341_p1);
    sensitive << ( r_V_fu_335_p2 );

    SC_METHOD(thread_tmp_103_1_fu_492_p1);
    sensitive << ( i_10_s_fu_486_p2 );

    SC_METHOD(thread_tmp_103_2_fu_557_p1);
    sensitive << ( i_10_1_fu_551_p2 );

    SC_METHOD(thread_tmp_103_3_fu_608_p1);
    sensitive << ( i_10_2_fu_602_p2 );

    SC_METHOD(thread_tmp_13_fu_705_p4);
    sensitive << ( grp_fu_942_p3 );

    SC_METHOD(thread_tmp_16_cast_fu_752_p1);
    sensitive << ( qb_assign_3_fu_746_p2 );

    SC_METHOD(thread_tmp_37_fu_357_p3);
    sensitive << ( i_reg_284 );

    SC_METHOD(thread_tmp_38_fu_369_p3);
    sensitive << ( i_reg_284 );

    SC_METHOD(thread_tmp_39_fu_381_p2);
    sensitive << ( p_shl1_cast_fu_377_p1 );
    sensitive << ( p_shl_cast_fu_365_p1 );

    SC_METHOD(thread_tmp_40_cast_fu_387_p1);
    sensitive << ( tmp_39_fu_381_p2 );

    SC_METHOD(thread_tmp_40_fu_446_p3);
    sensitive << ( i1_reg_308 );

    SC_METHOD(thread_tmp_41_fu_458_p3);
    sensitive << ( i1_reg_308 );

    SC_METHOD(thread_tmp_42_fu_470_p2);
    sensitive << ( p_shl9_cast_fu_466_p1 );
    sensitive << ( p_shl8_cast_fu_454_p1 );

    SC_METHOD(thread_tmp_43_fu_476_p2);
    sensitive << ( tmp_4_cast_reg_974 );
    sensitive << ( tmp_42_fu_470_p2 );

    SC_METHOD(thread_tmp_44_cast_fu_481_p1);
    sensitive << ( tmp_43_fu_476_p2 );

    SC_METHOD(thread_tmp_44_fu_497_p3);
    sensitive << ( i_10_s_fu_486_p2 );

    SC_METHOD(thread_tmp_45_fu_509_p3);
    sensitive << ( i_10_s_fu_486_p2 );

    SC_METHOD(thread_tmp_46_fu_521_p2);
    sensitive << ( p_shl7_cast_fu_517_p1 );
    sensitive << ( p_shl6_cast_fu_505_p1 );

    SC_METHOD(thread_tmp_47_fu_527_p2);
    sensitive << ( tmp_4_cast_reg_974 );
    sensitive << ( tmp_46_fu_521_p2 );

    SC_METHOD(thread_tmp_48_cast_fu_532_p1);
    sensitive << ( tmp_47_fu_527_p2 );

    SC_METHOD(thread_tmp_48_fu_562_p3);
    sensitive << ( i_10_1_fu_551_p2 );

    SC_METHOD(thread_tmp_49_fu_574_p3);
    sensitive << ( i_10_1_fu_551_p2 );

    SC_METHOD(thread_tmp_4_cast_fu_427_p1);
    sensitive << ( j_reg_296 );

    SC_METHOD(thread_tmp_50_fu_586_p2);
    sensitive << ( p_shl5_cast_fu_582_p1 );
    sensitive << ( p_shl4_cast_fu_570_p1 );

    SC_METHOD(thread_tmp_51_fu_592_p2);
    sensitive << ( tmp_4_cast_reg_974 );
    sensitive << ( tmp_50_fu_586_p2 );

    SC_METHOD(thread_tmp_52_cast_fu_597_p1);
    sensitive << ( tmp_51_fu_592_p2 );

    SC_METHOD(thread_tmp_52_fu_613_p3);
    sensitive << ( i_10_2_fu_602_p2 );

    SC_METHOD(thread_tmp_53_fu_625_p3);
    sensitive << ( i_10_2_fu_602_p2 );

    SC_METHOD(thread_tmp_54_fu_637_p2);
    sensitive << ( p_shl3_cast_fu_633_p1 );
    sensitive << ( p_shl2_cast_fu_621_p1 );

    SC_METHOD(thread_tmp_55_fu_643_p2);
    sensitive << ( tmp_4_cast_reg_974 );
    sensitive << ( tmp_54_fu_637_p2 );

    SC_METHOD(thread_tmp_56_cast_fu_648_p1);
    sensitive << ( tmp_55_fu_643_p2 );

    SC_METHOD(thread_tmp_57_fu_698_p3);
    sensitive << ( grp_fu_942_p3 );

    SC_METHOD(thread_tmp_59_fu_725_p1);
    sensitive << ( grp_fu_942_p3 );

    SC_METHOD(thread_tmp_5_fu_679_p1);
    sensitive << ( i2_reg_320 );

    SC_METHOD(thread_tmp_60_fu_762_p3);
    sensitive << ( p_Val2_13_fu_756_p2 );

    SC_METHOD(thread_tmp_61_fu_786_p1);
    sensitive << ( p_a_V_i_fu_770_p3 );

    SC_METHOD(thread_tmp_7_fu_838_p2);
    sensitive << ( isneg_reg_1098 );

    SC_METHOD(thread_tmp_8_fu_441_p1);
    sensitive << ( i1_reg_308 );

    SC_METHOD(thread_tmp_s_fu_392_p1);
    sensitive << ( i_reg_284 );

    SC_METHOD(thread_underflow_fu_866_p2);
    sensitive << ( isneg_reg_1098 );
    sensitive << ( brmerge39_i_i_fu_860_p2 );

    SC_METHOD(thread_underflow_not_fu_877_p2);
    sensitive << ( underflow_fu_866_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( out_V_V_full_n );
    sensitive << ( in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond6_fu_411_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_345_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( exitcond2_fu_435_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( exitcond_fu_667_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fc_layer1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, out_V_V_din, "(port)out_V_V_din");
    sc_trace(mVcdFile, out_V_V_full_n, "(port)out_V_V_full_n");
    sc_trace(mVcdFile, out_V_V_write, "(port)out_V_V_write");
    sc_trace(mVcdFile, in_V_V_dout, "(port)in_V_V_dout");
    sc_trace(mVcdFile, in_V_V_empty_n, "(port)in_V_V_empty_n");
    sc_trace(mVcdFile, in_V_V_read, "(port)in_V_V_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, fc_layer1_weights_V_address0, "fc_layer1_weights_V_address0");
    sc_trace(mVcdFile, fc_layer1_weights_V_ce0, "fc_layer1_weights_V_ce0");
    sc_trace(mVcdFile, fc_layer1_weights_V_q0, "fc_layer1_weights_V_q0");
    sc_trace(mVcdFile, fc_layer1_weights_V_address1, "fc_layer1_weights_V_address1");
    sc_trace(mVcdFile, fc_layer1_weights_V_ce1, "fc_layer1_weights_V_ce1");
    sc_trace(mVcdFile, fc_layer1_weights_V_q1, "fc_layer1_weights_V_q1");
    sc_trace(mVcdFile, fc_layer1_bias_V_address0, "fc_layer1_bias_V_address0");
    sc_trace(mVcdFile, fc_layer1_bias_V_ce0, "fc_layer1_bias_V_ce0");
    sc_trace(mVcdFile, fc_layer1_bias_V_q0, "fc_layer1_bias_V_q0");
    sc_trace(mVcdFile, out_V_V_blk_n, "out_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, in_V_V_blk_n, "in_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, exitcond6_fu_411_p2, "exitcond6_fu_411_p2");
    sc_trace(mVcdFile, read_temp_V_cast_fu_341_p1, "read_temp_V_cast_fu_341_p1");
    sc_trace(mVcdFile, read_temp_V_cast_reg_953, "read_temp_V_cast_reg_953");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, i_6_fu_351_p2, "i_6_fu_351_p2");
    sc_trace(mVcdFile, i_6_reg_961, "i_6_reg_961");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, exitcond5_fu_345_p2, "exitcond5_fu_345_p2");
    sc_trace(mVcdFile, tmp_4_cast_fu_427_p1, "tmp_4_cast_fu_427_p1");
    sc_trace(mVcdFile, tmp_4_cast_reg_974, "tmp_4_cast_reg_974");
    sc_trace(mVcdFile, ap_block_state4, "ap_block_state4");
    sc_trace(mVcdFile, p_1_cast_fu_431_p1, "p_1_cast_fu_431_p1");
    sc_trace(mVcdFile, p_1_cast_reg_982, "p_1_cast_reg_982");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, exitcond2_fu_435_p2, "exitcond2_fu_435_p2");
    sc_trace(mVcdFile, output_V_addr_11_reg_998, "output_V_addr_11_reg_998");
    sc_trace(mVcdFile, output_V_addr_12_reg_1009, "output_V_addr_12_reg_1009");
    sc_trace(mVcdFile, j_3_fu_537_p2, "j_3_fu_537_p2");
    sc_trace(mVcdFile, grp_fu_914_p3, "grp_fu_914_p3");
    sc_trace(mVcdFile, tmp_9_reg_1020, "tmp_9_reg_1020");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, grp_fu_921_p3, "grp_fu_921_p3");
    sc_trace(mVcdFile, tmp_104_1_reg_1025, "tmp_104_1_reg_1025");
    sc_trace(mVcdFile, output_V_addr_13_reg_1035, "output_V_addr_13_reg_1035");
    sc_trace(mVcdFile, output_V_addr_14_reg_1045, "output_V_addr_14_reg_1045");
    sc_trace(mVcdFile, i_10_3_fu_653_p2, "i_10_3_fu_653_p2");
    sc_trace(mVcdFile, i_10_3_reg_1050, "i_10_3_reg_1050");
    sc_trace(mVcdFile, grp_fu_928_p3, "grp_fu_928_p3");
    sc_trace(mVcdFile, tmp_104_2_reg_1055, "tmp_104_2_reg_1055");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, grp_fu_935_p3, "grp_fu_935_p3");
    sc_trace(mVcdFile, tmp_104_3_reg_1060, "tmp_104_3_reg_1060");
    sc_trace(mVcdFile, i_7_fu_673_p2, "i_7_fu_673_p2");
    sc_trace(mVcdFile, i_7_reg_1068, "i_7_reg_1068");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, exitcond_fu_667_p2, "exitcond_fu_667_p2");
    sc_trace(mVcdFile, p_Val2_s_fu_689_p2, "p_Val2_s_fu_689_p2");
    sc_trace(mVcdFile, p_Val2_s_reg_1083, "p_Val2_s_reg_1083");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, f_op_V_3_reg_1088, "f_op_V_3_reg_1088");
    sc_trace(mVcdFile, tmp_61_fu_786_p1, "tmp_61_fu_786_p1");
    sc_trace(mVcdFile, tmp_61_reg_1093, "tmp_61_reg_1093");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, isneg_reg_1098, "isneg_reg_1098");
    sc_trace(mVcdFile, tmp_14_reg_1104, "tmp_14_reg_1104");
    sc_trace(mVcdFile, output_V_address0, "output_V_address0");
    sc_trace(mVcdFile, output_V_ce0, "output_V_ce0");
    sc_trace(mVcdFile, output_V_we0, "output_V_we0");
    sc_trace(mVcdFile, output_V_d0, "output_V_d0");
    sc_trace(mVcdFile, output_V_q0, "output_V_q0");
    sc_trace(mVcdFile, output_V_address1, "output_V_address1");
    sc_trace(mVcdFile, output_V_ce1, "output_V_ce1");
    sc_trace(mVcdFile, output_V_we1, "output_V_we1");
    sc_trace(mVcdFile, output_V_d1, "output_V_d1");
    sc_trace(mVcdFile, output_V_q1, "output_V_q1");
    sc_trace(mVcdFile, i_reg_284, "i_reg_284");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, j_reg_296, "j_reg_296");
    sc_trace(mVcdFile, i1_reg_308, "i1_reg_308");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, i2_reg_320, "i2_reg_320");
    sc_trace(mVcdFile, tmp_40_cast_fu_387_p1, "tmp_40_cast_fu_387_p1");
    sc_trace(mVcdFile, tmp_s_fu_392_p1, "tmp_s_fu_392_p1");
    sc_trace(mVcdFile, tmp_44_cast_fu_481_p1, "tmp_44_cast_fu_481_p1");
    sc_trace(mVcdFile, tmp_8_fu_441_p1, "tmp_8_fu_441_p1");
    sc_trace(mVcdFile, tmp_48_cast_fu_532_p1, "tmp_48_cast_fu_532_p1");
    sc_trace(mVcdFile, tmp_103_1_fu_492_p1, "tmp_103_1_fu_492_p1");
    sc_trace(mVcdFile, tmp_52_cast_fu_597_p1, "tmp_52_cast_fu_597_p1");
    sc_trace(mVcdFile, tmp_103_2_fu_557_p1, "tmp_103_2_fu_557_p1");
    sc_trace(mVcdFile, tmp_56_cast_fu_648_p1, "tmp_56_cast_fu_648_p1");
    sc_trace(mVcdFile, tmp_103_3_fu_608_p1, "tmp_103_3_fu_608_p1");
    sc_trace(mVcdFile, tmp_5_fu_679_p1, "tmp_5_fu_679_p1");
    sc_trace(mVcdFile, p_9_cast_fu_406_p1, "p_9_cast_fu_406_p1");
    sc_trace(mVcdFile, lhs_V_fu_331_p0, "lhs_V_fu_331_p0");
    sc_trace(mVcdFile, lhs_V_fu_331_p1, "lhs_V_fu_331_p1");
    sc_trace(mVcdFile, r_V_fu_335_p2, "r_V_fu_335_p2");
    sc_trace(mVcdFile, tmp_37_fu_357_p3, "tmp_37_fu_357_p3");
    sc_trace(mVcdFile, tmp_38_fu_369_p3, "tmp_38_fu_369_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_377_p1, "p_shl1_cast_fu_377_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_365_p1, "p_shl_cast_fu_365_p1");
    sc_trace(mVcdFile, tmp_39_fu_381_p2, "tmp_39_fu_381_p2");
    sc_trace(mVcdFile, p_9_fu_401_p0, "p_9_fu_401_p0");
    sc_trace(mVcdFile, p_9_fu_401_p1, "p_9_fu_401_p1");
    sc_trace(mVcdFile, p_9_fu_401_p2, "p_9_fu_401_p2");
    sc_trace(mVcdFile, lhs_V_3_fu_417_p1, "lhs_V_3_fu_417_p1");
    sc_trace(mVcdFile, r_V_5_fu_421_p2, "r_V_5_fu_421_p2");
    sc_trace(mVcdFile, tmp_40_fu_446_p3, "tmp_40_fu_446_p3");
    sc_trace(mVcdFile, tmp_41_fu_458_p3, "tmp_41_fu_458_p3");
    sc_trace(mVcdFile, p_shl9_cast_fu_466_p1, "p_shl9_cast_fu_466_p1");
    sc_trace(mVcdFile, p_shl8_cast_fu_454_p1, "p_shl8_cast_fu_454_p1");
    sc_trace(mVcdFile, tmp_42_fu_470_p2, "tmp_42_fu_470_p2");
    sc_trace(mVcdFile, tmp_43_fu_476_p2, "tmp_43_fu_476_p2");
    sc_trace(mVcdFile, i_10_s_fu_486_p2, "i_10_s_fu_486_p2");
    sc_trace(mVcdFile, tmp_44_fu_497_p3, "tmp_44_fu_497_p3");
    sc_trace(mVcdFile, tmp_45_fu_509_p3, "tmp_45_fu_509_p3");
    sc_trace(mVcdFile, p_shl7_cast_fu_517_p1, "p_shl7_cast_fu_517_p1");
    sc_trace(mVcdFile, p_shl6_cast_fu_505_p1, "p_shl6_cast_fu_505_p1");
    sc_trace(mVcdFile, tmp_46_fu_521_p2, "tmp_46_fu_521_p2");
    sc_trace(mVcdFile, tmp_47_fu_527_p2, "tmp_47_fu_527_p2");
    sc_trace(mVcdFile, i_10_1_fu_551_p2, "i_10_1_fu_551_p2");
    sc_trace(mVcdFile, tmp_48_fu_562_p3, "tmp_48_fu_562_p3");
    sc_trace(mVcdFile, tmp_49_fu_574_p3, "tmp_49_fu_574_p3");
    sc_trace(mVcdFile, p_shl5_cast_fu_582_p1, "p_shl5_cast_fu_582_p1");
    sc_trace(mVcdFile, p_shl4_cast_fu_570_p1, "p_shl4_cast_fu_570_p1");
    sc_trace(mVcdFile, tmp_50_fu_586_p2, "tmp_50_fu_586_p2");
    sc_trace(mVcdFile, tmp_51_fu_592_p2, "tmp_51_fu_592_p2");
    sc_trace(mVcdFile, i_10_2_fu_602_p2, "i_10_2_fu_602_p2");
    sc_trace(mVcdFile, tmp_52_fu_613_p3, "tmp_52_fu_613_p3");
    sc_trace(mVcdFile, tmp_53_fu_625_p3, "tmp_53_fu_625_p3");
    sc_trace(mVcdFile, p_shl3_cast_fu_633_p1, "p_shl3_cast_fu_633_p1");
    sc_trace(mVcdFile, p_shl2_cast_fu_621_p1, "p_shl2_cast_fu_621_p1");
    sc_trace(mVcdFile, tmp_54_fu_637_p2, "tmp_54_fu_637_p2");
    sc_trace(mVcdFile, tmp_55_fu_643_p2, "tmp_55_fu_643_p2");
    sc_trace(mVcdFile, p_Val2_s_fu_689_p1, "p_Val2_s_fu_689_p1");
    sc_trace(mVcdFile, grp_fu_942_p3, "grp_fu_942_p3");
    sc_trace(mVcdFile, tmp_13_fu_705_p4, "tmp_13_fu_705_p4");
    sc_trace(mVcdFile, tmp_59_fu_725_p1, "tmp_59_fu_725_p1");
    sc_trace(mVcdFile, tmp_57_fu_698_p3, "tmp_57_fu_698_p3");
    sc_trace(mVcdFile, r_fu_728_p2, "r_fu_728_p2");
    sc_trace(mVcdFile, not_s_i_i3_fu_734_p2, "not_s_i_i3_fu_734_p2");
    sc_trace(mVcdFile, r_i_i3_fu_740_p2, "r_i_i3_fu_740_p2");
    sc_trace(mVcdFile, qbit_fu_718_p3, "qbit_fu_718_p3");
    sc_trace(mVcdFile, qb_assign_3_fu_746_p2, "qb_assign_3_fu_746_p2");
    sc_trace(mVcdFile, tmp_16_cast_fu_752_p1, "tmp_16_cast_fu_752_p1");
    sc_trace(mVcdFile, p_Val2_15_cast_fu_714_p1, "p_Val2_15_cast_fu_714_p1");
    sc_trace(mVcdFile, p_Val2_13_fu_756_p2, "p_Val2_13_fu_756_p2");
    sc_trace(mVcdFile, tmp_60_fu_762_p3, "tmp_60_fu_762_p3");
    sc_trace(mVcdFile, p_a_V_i_fu_770_p3, "p_a_V_i_fu_770_p3");
    sc_trace(mVcdFile, p_a_V_i_cast1_fu_778_p1, "p_a_V_i_cast1_fu_778_p1");
    sc_trace(mVcdFile, p_a_V_i_cast_fu_782_p1, "p_a_V_i_cast_fu_782_p1");
    sc_trace(mVcdFile, r_V_7_fu_790_p2, "r_V_7_fu_790_p2");
    sc_trace(mVcdFile, p_Val2_15_fu_814_p2, "p_Val2_15_fu_814_p2");
    sc_trace(mVcdFile, newsignbit_fu_819_p3, "newsignbit_fu_819_p3");
    sc_trace(mVcdFile, p_not_i_i_fu_827_p2, "p_not_i_i_fu_827_p2");
    sc_trace(mVcdFile, brmerge_i_i_fu_832_p2, "brmerge_i_i_fu_832_p2");
    sc_trace(mVcdFile, tmp_7_fu_838_p2, "tmp_7_fu_838_p2");
    sc_trace(mVcdFile, p_not38_i_i_fu_855_p2, "p_not38_i_i_fu_855_p2");
    sc_trace(mVcdFile, newsignbit_0_not_i_i_fu_849_p2, "newsignbit_0_not_i_i_fu_849_p2");
    sc_trace(mVcdFile, brmerge39_i_i_fu_860_p2, "brmerge39_i_i_fu_860_p2");
    sc_trace(mVcdFile, underflow_fu_866_p2, "underflow_fu_866_p2");
    sc_trace(mVcdFile, overflow_fu_843_p2, "overflow_fu_843_p2");
    sc_trace(mVcdFile, underflow_not_fu_877_p2, "underflow_not_fu_877_p2");
    sc_trace(mVcdFile, brmerge_i_i_i_fu_871_p2, "brmerge_i_i_i_fu_871_p2");
    sc_trace(mVcdFile, brmerge_fu_883_p2, "brmerge_fu_883_p2");
    sc_trace(mVcdFile, p_Val2_35_mux_fu_889_p3, "p_Val2_35_mux_fu_889_p3");
    sc_trace(mVcdFile, p_Val2_s_525_fu_897_p3, "p_Val2_s_525_fu_897_p3");
    sc_trace(mVcdFile, grp_fu_914_p1, "grp_fu_914_p1");
    sc_trace(mVcdFile, grp_fu_921_p1, "grp_fu_921_p1");
    sc_trace(mVcdFile, grp_fu_928_p1, "grp_fu_928_p1");
    sc_trace(mVcdFile, grp_fu_935_p1, "grp_fu_935_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

fc_layer1::~fc_layer1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete fc_layer1_weights_V_U;
    delete fc_layer1_bias_V_U;
    delete output_V_U;
    delete nnet_mac_muladd_8b9t_U56;
    delete nnet_mac_muladd_8b9t_U57;
    delete nnet_mac_muladd_8b9t_U58;
    delete nnet_mac_muladd_8b9t_U59;
    delete nnet_mac_muladd_3cau_U60;
}

void fc_layer1::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv31_816A0;
}

void fc_layer1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                    esl_seteq<1,1,1>(exitcond_fu_667_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i1_reg_308 = i_10_3_reg_1050.read();
    } else if ((!(esl_seteq<1,1,1>(exitcond6_fu_411_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0)) && 
                esl_seteq<1,1,1>(exitcond6_fu_411_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        i1_reg_308 = ap_const_lv7_0;
    }
    if ((!(esl_seteq<1,1,1>(exitcond6_fu_411_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0)) && 
         esl_seteq<1,1,1>(exitcond6_fu_411_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        i2_reg_320 = ap_const_lv7_0;
    } else if ((esl_seteq<1,1,1>(out_V_V_full_n.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        i2_reg_320 = i_7_reg_1068.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_reg_284 = i_6_reg_961.read();
    } else if ((!(esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        i_reg_284 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(exitcond5_fu_345_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        j_reg_296 = ap_const_lv10_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_435_p2.read(), ap_const_lv1_1))) {
        j_reg_296 = j_3_fu_537_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        f_op_V_3_reg_1088 = fc_layer1_bias_V_q0.read();
        p_Val2_s_reg_1083 = p_Val2_s_fu_689_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_10_3_reg_1050 = i_10_3_fu_653_p2.read();
        output_V_addr_13_reg_1035 =  (sc_lv<7>) (tmp_103_2_fu_557_p1.read());
        output_V_addr_14_reg_1045 =  (sc_lv<7>) (tmp_103_3_fu_608_p1.read());
        tmp_104_1_reg_1025 = grp_fu_921_p3.read();
        tmp_9_reg_1020 = grp_fu_914_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_6_reg_961 = i_6_fu_351_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        i_7_reg_1068 = i_7_fu_673_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        isneg_reg_1098 = r_V_7_fu_790_p2.read().range(23, 23);
        tmp_14_reg_1104 = r_V_7_fu_790_p2.read().range(23, 8);
        tmp_61_reg_1093 = tmp_61_fu_786_p1.read();
    }
    if ((esl_seteq<1,1,1>(exitcond2_fu_435_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        output_V_addr_11_reg_998 =  (sc_lv<7>) (tmp_8_fu_441_p1.read());
        output_V_addr_12_reg_1009 =  (sc_lv<7>) (tmp_103_1_fu_492_p1.read());
    }
    if ((!(esl_seteq<1,1,1>(exitcond6_fu_411_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(exitcond6_fu_411_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        p_1_cast_reg_982 = p_1_cast_fu_431_p1.read();
        tmp_4_cast_reg_974 = tmp_4_cast_fu_427_p1.read();
    }
    if ((!(esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        read_temp_V_cast_reg_953 = read_temp_V_cast_fu_341_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        tmp_104_2_reg_1055 = grp_fu_928_p3.read();
        tmp_104_3_reg_1060 = grp_fu_935_p3.read();
    }
}

void fc_layer1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void fc_layer1::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void fc_layer1::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void fc_layer1::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void fc_layer1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void fc_layer1::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void fc_layer1::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void fc_layer1::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void fc_layer1::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void fc_layer1::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void fc_layer1::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void fc_layer1::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void fc_layer1::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void fc_layer1::thread_ap_block_state4() {
    ap_block_state4 = (esl_seteq<1,1,1>(exitcond6_fu_411_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0));
}

void fc_layer1::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_667_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void fc_layer1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void fc_layer1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_667_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void fc_layer1::thread_brmerge39_i_i_fu_860_p2() {
    brmerge39_i_i_fu_860_p2 = (p_not38_i_i_fu_855_p2.read() | newsignbit_0_not_i_i_fu_849_p2.read());
}

void fc_layer1::thread_brmerge_fu_883_p2() {
    brmerge_fu_883_p2 = (overflow_fu_843_p2.read() | underflow_not_fu_877_p2.read());
}

void fc_layer1::thread_brmerge_i_i_fu_832_p2() {
    brmerge_i_i_fu_832_p2 = (newsignbit_fu_819_p3.read() | p_not_i_i_fu_827_p2.read());
}

void fc_layer1::thread_brmerge_i_i_i_fu_871_p2() {
    brmerge_i_i_i_fu_871_p2 = (underflow_fu_866_p2.read() | overflow_fu_843_p2.read());
}

void fc_layer1::thread_exitcond2_fu_435_p2() {
    exitcond2_fu_435_p2 = (!i1_reg_308.read().is_01() || !ap_const_lv7_78.is_01())? sc_lv<1>(): sc_lv<1>(i1_reg_308.read() == ap_const_lv7_78);
}

void fc_layer1::thread_exitcond5_fu_345_p2() {
    exitcond5_fu_345_p2 = (!i_reg_284.read().is_01() || !ap_const_lv7_78.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_284.read() == ap_const_lv7_78);
}

void fc_layer1::thread_exitcond6_fu_411_p2() {
    exitcond6_fu_411_p2 = (!j_reg_296.read().is_01() || !ap_const_lv10_240.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_296.read() == ap_const_lv10_240);
}

void fc_layer1::thread_exitcond_fu_667_p2() {
    exitcond_fu_667_p2 = (!i2_reg_320.read().is_01() || !ap_const_lv7_78.is_01())? sc_lv<1>(): sc_lv<1>(i2_reg_320.read() == ap_const_lv7_78);
}

void fc_layer1::thread_fc_layer1_bias_V_address0() {
    fc_layer1_bias_V_address0 =  (sc_lv<7>) (tmp_5_fu_679_p1.read());
}

void fc_layer1::thread_fc_layer1_bias_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        fc_layer1_bias_V_ce0 = ap_const_logic_1;
    } else {
        fc_layer1_bias_V_ce0 = ap_const_logic_0;
    }
}

void fc_layer1::thread_fc_layer1_weights_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        fc_layer1_weights_V_address0 =  (sc_lv<17>) (tmp_52_cast_fu_597_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        fc_layer1_weights_V_address0 =  (sc_lv<17>) (tmp_44_cast_fu_481_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        fc_layer1_weights_V_address0 =  (sc_lv<17>) (tmp_40_cast_fu_387_p1.read());
    } else {
        fc_layer1_weights_V_address0 = "XXXXXXXXXXXXXXXXX";
    }
}

void fc_layer1::thread_fc_layer1_weights_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        fc_layer1_weights_V_address1 =  (sc_lv<17>) (tmp_56_cast_fu_648_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        fc_layer1_weights_V_address1 =  (sc_lv<17>) (tmp_48_cast_fu_532_p1.read());
    } else {
        fc_layer1_weights_V_address1 = "XXXXXXXXXXXXXXXXX";
    }
}

void fc_layer1::thread_fc_layer1_weights_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        fc_layer1_weights_V_ce0 = ap_const_logic_1;
    } else {
        fc_layer1_weights_V_ce0 = ap_const_logic_0;
    }
}

void fc_layer1::thread_fc_layer1_weights_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        fc_layer1_weights_V_ce1 = ap_const_logic_1;
    } else {
        fc_layer1_weights_V_ce1 = ap_const_logic_0;
    }
}

void fc_layer1::thread_grp_fu_914_p1() {
    grp_fu_914_p1 =  (sc_lv<9>) (p_1_cast_reg_982.read());
}

void fc_layer1::thread_grp_fu_921_p1() {
    grp_fu_921_p1 =  (sc_lv<9>) (p_1_cast_reg_982.read());
}

void fc_layer1::thread_grp_fu_928_p1() {
    grp_fu_928_p1 =  (sc_lv<9>) (p_1_cast_reg_982.read());
}

void fc_layer1::thread_grp_fu_935_p1() {
    grp_fu_935_p1 =  (sc_lv<9>) (p_1_cast_reg_982.read());
}

void fc_layer1::thread_i_10_1_fu_551_p2() {
    i_10_1_fu_551_p2 = (i1_reg_308.read() | ap_const_lv7_2);
}

void fc_layer1::thread_i_10_2_fu_602_p2() {
    i_10_2_fu_602_p2 = (i1_reg_308.read() | ap_const_lv7_3);
}

void fc_layer1::thread_i_10_3_fu_653_p2() {
    i_10_3_fu_653_p2 = (!i1_reg_308.read().is_01() || !ap_const_lv7_4.is_01())? sc_lv<7>(): (sc_biguint<7>(i1_reg_308.read()) + sc_biguint<7>(ap_const_lv7_4));
}

void fc_layer1::thread_i_10_s_fu_486_p2() {
    i_10_s_fu_486_p2 = (i1_reg_308.read() | ap_const_lv7_1);
}

void fc_layer1::thread_i_6_fu_351_p2() {
    i_6_fu_351_p2 = (!i_reg_284.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i_reg_284.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void fc_layer1::thread_i_7_fu_673_p2() {
    i_7_fu_673_p2 = (!i2_reg_320.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i2_reg_320.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void fc_layer1::thread_in_V_V_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(exitcond6_fu_411_p2.read(), ap_const_lv1_0)))) {
        in_V_V_blk_n = in_V_V_empty_n.read();
    } else {
        in_V_V_blk_n = ap_const_logic_1;
    }
}

void fc_layer1::thread_in_V_V_read() {
    if (((!(esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (!(esl_seteq<1,1,1>(exitcond6_fu_411_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(exitcond6_fu_411_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())))) {
        in_V_V_read = ap_const_logic_1;
    } else {
        in_V_V_read = ap_const_logic_0;
    }
}

void fc_layer1::thread_j_3_fu_537_p2() {
    j_3_fu_537_p2 = (!j_reg_296.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(j_reg_296.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void fc_layer1::thread_lhs_V_3_fu_417_p1() {
    lhs_V_3_fu_417_p1 = esl_sext<9,8>(in_V_V_dout.read());
}

void fc_layer1::thread_lhs_V_fu_331_p0() {
    lhs_V_fu_331_p0 = in_V_V_dout.read();
}

void fc_layer1::thread_lhs_V_fu_331_p1() {
    lhs_V_fu_331_p1 = esl_sext<9,8>(lhs_V_fu_331_p0.read());
}

void fc_layer1::thread_newsignbit_0_not_i_i_fu_849_p2() {
    newsignbit_0_not_i_i_fu_849_p2 = (newsignbit_fu_819_p3.read() ^ ap_const_lv1_1);
}

void fc_layer1::thread_newsignbit_fu_819_p3() {
    newsignbit_fu_819_p3 = p_Val2_15_fu_814_p2.read().range(7, 7);
}

void fc_layer1::thread_not_s_i_i3_fu_734_p2() {
    not_s_i_i3_fu_734_p2 = (tmp_57_fu_698_p3.read() ^ ap_const_lv1_1);
}

void fc_layer1::thread_out_V_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        out_V_V_blk_n = out_V_V_full_n.read();
    } else {
        out_V_V_blk_n = ap_const_logic_1;
    }
}

void fc_layer1::thread_out_V_V_din() {
    out_V_V_din = (!brmerge_fu_883_p2.read()[0].is_01())? sc_lv<8>(): ((brmerge_fu_883_p2.read()[0].to_bool())? p_Val2_35_mux_fu_889_p3.read(): p_Val2_s_525_fu_897_p3.read());
}

void fc_layer1::thread_out_V_V_write() {
    if ((esl_seteq<1,1,1>(out_V_V_full_n.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        out_V_V_write = ap_const_logic_1;
    } else {
        out_V_V_write = ap_const_logic_0;
    }
}

void fc_layer1::thread_output_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        output_V_address0 = output_V_addr_14_reg_1045.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_V_address0 = output_V_addr_12_reg_1009.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_V_address0 =  (sc_lv<7>) (tmp_103_3_fu_608_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        output_V_address0 =  (sc_lv<7>) (tmp_8_fu_441_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        output_V_address0 =  (sc_lv<7>) (tmp_s_fu_392_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        output_V_address0 =  (sc_lv<7>) (ap_const_lv64_0);
    } else {
        output_V_address0 =  (sc_lv<7>) ("XXXXXXX");
    }
}

void fc_layer1::thread_output_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        output_V_address1 =  (sc_lv<7>) (tmp_5_fu_679_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        output_V_address1 = output_V_addr_13_reg_1035.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_V_address1 = output_V_addr_11_reg_998.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_V_address1 =  (sc_lv<7>) (tmp_103_2_fu_557_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        output_V_address1 =  (sc_lv<7>) (tmp_103_1_fu_492_p1.read());
    } else {
        output_V_address1 =  (sc_lv<7>) ("XXXXXXX");
    }
}

void fc_layer1::thread_output_V_ce0() {
    if (((!(esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        output_V_ce0 = ap_const_logic_1;
    } else {
        output_V_ce0 = ap_const_logic_0;
    }
}

void fc_layer1::thread_output_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        output_V_ce1 = ap_const_logic_1;
    } else {
        output_V_ce1 = ap_const_logic_0;
    }
}

void fc_layer1::thread_output_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        output_V_d0 = tmp_104_3_reg_1060.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_V_d0 = tmp_104_1_reg_1025.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        output_V_d0 = p_9_cast_fu_406_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        output_V_d0 = ap_const_lv24_0;
    } else {
        output_V_d0 =  (sc_lv<24>) ("XXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fc_layer1::thread_output_V_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        output_V_d1 = tmp_104_2_reg_1055.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_V_d1 = tmp_9_reg_1020.read();
    } else {
        output_V_d1 =  (sc_lv<24>) ("XXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fc_layer1::thread_output_V_we0() {
    if (((!(esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        output_V_we0 = ap_const_logic_1;
    } else {
        output_V_we0 = ap_const_logic_0;
    }
}

void fc_layer1::thread_output_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        output_V_we1 = ap_const_logic_1;
    } else {
        output_V_we1 = ap_const_logic_0;
    }
}

void fc_layer1::thread_overflow_fu_843_p2() {
    overflow_fu_843_p2 = (brmerge_i_i_fu_832_p2.read() & tmp_7_fu_838_p2.read());
}

void fc_layer1::thread_p_1_cast_fu_431_p1() {
    p_1_cast_fu_431_p1 = esl_sext<17,9>(r_V_5_fu_421_p2.read());
}

void fc_layer1::thread_p_9_cast_fu_406_p1() {
    p_9_cast_fu_406_p1 = esl_sext<24,17>(p_9_fu_401_p2.read());
}

void fc_layer1::thread_p_9_fu_401_p0() {
    p_9_fu_401_p0 = fc_layer1_weights_V_q0.read();
}

void fc_layer1::thread_p_9_fu_401_p1() {
    p_9_fu_401_p1 =  (sc_lv<9>) (read_temp_V_cast_reg_953.read());
}

void fc_layer1::thread_p_9_fu_401_p2() {
    p_9_fu_401_p2 = (!p_9_fu_401_p0.read().is_01() || !p_9_fu_401_p1.read().is_01())? sc_lv<17>(): sc_bigint<8>(p_9_fu_401_p0.read()) * sc_bigint<9>(p_9_fu_401_p1.read());
}

void fc_layer1::thread_p_Val2_13_fu_756_p2() {
    p_Val2_13_fu_756_p2 = (!tmp_16_cast_fu_752_p1.read().is_01() || !p_Val2_15_cast_fu_714_p1.read().is_01())? sc_lv<17>(): (sc_biguint<17>(tmp_16_cast_fu_752_p1.read()) + sc_bigint<17>(p_Val2_15_cast_fu_714_p1.read()));
}

void fc_layer1::thread_p_Val2_15_cast_fu_714_p1() {
    p_Val2_15_cast_fu_714_p1 = esl_sext<17,16>(tmp_13_fu_705_p4.read());
}

void fc_layer1::thread_p_Val2_15_fu_814_p2() {
    p_Val2_15_fu_814_p2 = (!ap_const_lv8_FE.is_01() || !tmp_61_reg_1093.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_FE) + sc_biguint<8>(tmp_61_reg_1093.read()));
}

void fc_layer1::thread_p_Val2_35_mux_fu_889_p3() {
    p_Val2_35_mux_fu_889_p3 = (!brmerge_i_i_i_fu_871_p2.read()[0].is_01())? sc_lv<8>(): ((brmerge_i_i_i_fu_871_p2.read()[0].to_bool())? ap_const_lv8_7F: p_Val2_15_fu_814_p2.read());
}

void fc_layer1::thread_p_Val2_s_525_fu_897_p3() {
    p_Val2_s_525_fu_897_p3 = (!underflow_fu_866_p2.read()[0].is_01())? sc_lv<8>(): ((underflow_fu_866_p2.read()[0].to_bool())? ap_const_lv8_80: p_Val2_15_fu_814_p2.read());
}

void fc_layer1::thread_p_Val2_s_fu_689_p1() {
    p_Val2_s_fu_689_p1 = output_V_q1.read();
}

void fc_layer1::thread_p_Val2_s_fu_689_p2() {
    p_Val2_s_fu_689_p2 = (!ap_const_lv44_8169D.is_01() || !p_Val2_s_fu_689_p1.read().is_01())? sc_lv<44>(): sc_biguint<44>(ap_const_lv44_8169D) * sc_bigint<24>(p_Val2_s_fu_689_p1.read());
}

void fc_layer1::thread_p_a_V_i_cast1_fu_778_p1() {
    p_a_V_i_cast1_fu_778_p1 = esl_sext<23,17>(p_a_V_i_fu_770_p3.read());
}

void fc_layer1::thread_p_a_V_i_cast_fu_782_p1() {
    p_a_V_i_cast_fu_782_p1 = esl_zext<24,23>(p_a_V_i_cast1_fu_778_p1.read());
}

void fc_layer1::thread_p_a_V_i_fu_770_p3() {
    p_a_V_i_fu_770_p3 = (!tmp_60_fu_762_p3.read()[0].is_01())? sc_lv<17>(): ((tmp_60_fu_762_p3.read()[0].to_bool())? ap_const_lv17_0: p_Val2_13_fu_756_p2.read());
}

void fc_layer1::thread_p_not38_i_i_fu_855_p2() {
    p_not38_i_i_fu_855_p2 = (!tmp_14_reg_1104.read().is_01() || !ap_const_lv16_FFFF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_14_reg_1104.read() != ap_const_lv16_FFFF);
}

void fc_layer1::thread_p_not_i_i_fu_827_p2() {
    p_not_i_i_fu_827_p2 = (!tmp_14_reg_1104.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_14_reg_1104.read() != ap_const_lv16_0);
}

void fc_layer1::thread_p_shl1_cast_fu_377_p1() {
    p_shl1_cast_fu_377_p1 = esl_zext<17,13>(tmp_38_fu_369_p3.read());
}

void fc_layer1::thread_p_shl2_cast_fu_621_p1() {
    p_shl2_cast_fu_621_p1 = esl_zext<17,16>(tmp_52_fu_613_p3.read());
}

void fc_layer1::thread_p_shl3_cast_fu_633_p1() {
    p_shl3_cast_fu_633_p1 = esl_zext<17,13>(tmp_53_fu_625_p3.read());
}

void fc_layer1::thread_p_shl4_cast_fu_570_p1() {
    p_shl4_cast_fu_570_p1 = esl_zext<17,16>(tmp_48_fu_562_p3.read());
}

void fc_layer1::thread_p_shl5_cast_fu_582_p1() {
    p_shl5_cast_fu_582_p1 = esl_zext<17,13>(tmp_49_fu_574_p3.read());
}

void fc_layer1::thread_p_shl6_cast_fu_505_p1() {
    p_shl6_cast_fu_505_p1 = esl_zext<17,16>(tmp_44_fu_497_p3.read());
}

void fc_layer1::thread_p_shl7_cast_fu_517_p1() {
    p_shl7_cast_fu_517_p1 = esl_zext<17,13>(tmp_45_fu_509_p3.read());
}

void fc_layer1::thread_p_shl8_cast_fu_454_p1() {
    p_shl8_cast_fu_454_p1 = esl_zext<17,16>(tmp_40_fu_446_p3.read());
}

void fc_layer1::thread_p_shl9_cast_fu_466_p1() {
    p_shl9_cast_fu_466_p1 = esl_zext<17,13>(tmp_41_fu_458_p3.read());
}

void fc_layer1::thread_p_shl_cast_fu_365_p1() {
    p_shl_cast_fu_365_p1 = esl_zext<17,16>(tmp_37_fu_357_p3.read());
}

void fc_layer1::thread_qb_assign_3_fu_746_p2() {
    qb_assign_3_fu_746_p2 = (r_i_i3_fu_740_p2.read() & qbit_fu_718_p3.read());
}

void fc_layer1::thread_qbit_fu_718_p3() {
    qbit_fu_718_p3 = grp_fu_942_p3.read().range(27, 27);
}

void fc_layer1::thread_r_V_5_fu_421_p2() {
    r_V_5_fu_421_p2 = (!lhs_V_3_fu_417_p1.read().is_01() || !ap_const_lv9_2.is_01())? sc_lv<9>(): (sc_bigint<9>(lhs_V_3_fu_417_p1.read()) + sc_biguint<9>(ap_const_lv9_2));
}

void fc_layer1::thread_r_V_7_fu_790_p2() {
    r_V_7_fu_790_p2 = (!ap_const_lv24_FFFFFE.is_01() || !p_a_V_i_cast_fu_782_p1.read().is_01())? sc_lv<24>(): (sc_bigint<24>(ap_const_lv24_FFFFFE) + sc_biguint<24>(p_a_V_i_cast_fu_782_p1.read()));
}

void fc_layer1::thread_r_V_fu_335_p2() {
    r_V_fu_335_p2 = (!lhs_V_fu_331_p1.read().is_01() || !ap_const_lv9_2.is_01())? sc_lv<9>(): (sc_bigint<9>(lhs_V_fu_331_p1.read()) + sc_biguint<9>(ap_const_lv9_2));
}

void fc_layer1::thread_r_fu_728_p2() {
    r_fu_728_p2 = (!tmp_59_fu_725_p1.read().is_01() || !ap_const_lv27_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_59_fu_725_p1.read() != ap_const_lv27_0);
}

void fc_layer1::thread_r_i_i3_fu_740_p2() {
    r_i_i3_fu_740_p2 = (r_fu_728_p2.read() | not_s_i_i3_fu_734_p2.read());
}

void fc_layer1::thread_read_temp_V_cast_fu_341_p1() {
    read_temp_V_cast_fu_341_p1 = esl_sext<17,9>(r_V_fu_335_p2.read());
}

void fc_layer1::thread_tmp_103_1_fu_492_p1() {
    tmp_103_1_fu_492_p1 = esl_zext<64,7>(i_10_s_fu_486_p2.read());
}

void fc_layer1::thread_tmp_103_2_fu_557_p1() {
    tmp_103_2_fu_557_p1 = esl_zext<64,7>(i_10_1_fu_551_p2.read());
}

void fc_layer1::thread_tmp_103_3_fu_608_p1() {
    tmp_103_3_fu_608_p1 = esl_zext<64,7>(i_10_2_fu_602_p2.read());
}

void fc_layer1::thread_tmp_13_fu_705_p4() {
    tmp_13_fu_705_p4 = grp_fu_942_p3.read().range(43, 28);
}

void fc_layer1::thread_tmp_16_cast_fu_752_p1() {
    tmp_16_cast_fu_752_p1 = esl_zext<17,1>(qb_assign_3_fu_746_p2.read());
}

void fc_layer1::thread_tmp_37_fu_357_p3() {
    tmp_37_fu_357_p3 = esl_concat<7,9>(i_reg_284.read(), ap_const_lv9_0);
}

void fc_layer1::thread_tmp_38_fu_369_p3() {
    tmp_38_fu_369_p3 = esl_concat<7,6>(i_reg_284.read(), ap_const_lv6_0);
}

void fc_layer1::thread_tmp_39_fu_381_p2() {
    tmp_39_fu_381_p2 = (!p_shl1_cast_fu_377_p1.read().is_01() || !p_shl_cast_fu_365_p1.read().is_01())? sc_lv<17>(): (sc_biguint<17>(p_shl1_cast_fu_377_p1.read()) + sc_biguint<17>(p_shl_cast_fu_365_p1.read()));
}

void fc_layer1::thread_tmp_40_cast_fu_387_p1() {
    tmp_40_cast_fu_387_p1 = esl_zext<64,17>(tmp_39_fu_381_p2.read());
}

void fc_layer1::thread_tmp_40_fu_446_p3() {
    tmp_40_fu_446_p3 = esl_concat<7,9>(i1_reg_308.read(), ap_const_lv9_0);
}

void fc_layer1::thread_tmp_41_fu_458_p3() {
    tmp_41_fu_458_p3 = esl_concat<7,6>(i1_reg_308.read(), ap_const_lv6_0);
}

void fc_layer1::thread_tmp_42_fu_470_p2() {
    tmp_42_fu_470_p2 = (!p_shl9_cast_fu_466_p1.read().is_01() || !p_shl8_cast_fu_454_p1.read().is_01())? sc_lv<17>(): (sc_biguint<17>(p_shl9_cast_fu_466_p1.read()) + sc_biguint<17>(p_shl8_cast_fu_454_p1.read()));
}

void fc_layer1::thread_tmp_43_fu_476_p2() {
    tmp_43_fu_476_p2 = (!tmp_42_fu_470_p2.read().is_01() || !tmp_4_cast_reg_974.read().is_01())? sc_lv<17>(): (sc_biguint<17>(tmp_42_fu_470_p2.read()) + sc_biguint<17>(tmp_4_cast_reg_974.read()));
}

void fc_layer1::thread_tmp_44_cast_fu_481_p1() {
    tmp_44_cast_fu_481_p1 = esl_zext<64,17>(tmp_43_fu_476_p2.read());
}

void fc_layer1::thread_tmp_44_fu_497_p3() {
    tmp_44_fu_497_p3 = esl_concat<7,9>(i_10_s_fu_486_p2.read(), ap_const_lv9_0);
}

void fc_layer1::thread_tmp_45_fu_509_p3() {
    tmp_45_fu_509_p3 = esl_concat<7,6>(i_10_s_fu_486_p2.read(), ap_const_lv6_0);
}

void fc_layer1::thread_tmp_46_fu_521_p2() {
    tmp_46_fu_521_p2 = (!p_shl7_cast_fu_517_p1.read().is_01() || !p_shl6_cast_fu_505_p1.read().is_01())? sc_lv<17>(): (sc_biguint<17>(p_shl7_cast_fu_517_p1.read()) + sc_biguint<17>(p_shl6_cast_fu_505_p1.read()));
}

void fc_layer1::thread_tmp_47_fu_527_p2() {
    tmp_47_fu_527_p2 = (!tmp_46_fu_521_p2.read().is_01() || !tmp_4_cast_reg_974.read().is_01())? sc_lv<17>(): (sc_biguint<17>(tmp_46_fu_521_p2.read()) + sc_biguint<17>(tmp_4_cast_reg_974.read()));
}

void fc_layer1::thread_tmp_48_cast_fu_532_p1() {
    tmp_48_cast_fu_532_p1 = esl_zext<64,17>(tmp_47_fu_527_p2.read());
}

void fc_layer1::thread_tmp_48_fu_562_p3() {
    tmp_48_fu_562_p3 = esl_concat<7,9>(i_10_1_fu_551_p2.read(), ap_const_lv9_0);
}

void fc_layer1::thread_tmp_49_fu_574_p3() {
    tmp_49_fu_574_p3 = esl_concat<7,6>(i_10_1_fu_551_p2.read(), ap_const_lv6_0);
}

void fc_layer1::thread_tmp_4_cast_fu_427_p1() {
    tmp_4_cast_fu_427_p1 = esl_zext<17,10>(j_reg_296.read());
}

void fc_layer1::thread_tmp_50_fu_586_p2() {
    tmp_50_fu_586_p2 = (!p_shl5_cast_fu_582_p1.read().is_01() || !p_shl4_cast_fu_570_p1.read().is_01())? sc_lv<17>(): (sc_biguint<17>(p_shl5_cast_fu_582_p1.read()) + sc_biguint<17>(p_shl4_cast_fu_570_p1.read()));
}

void fc_layer1::thread_tmp_51_fu_592_p2() {
    tmp_51_fu_592_p2 = (!tmp_50_fu_586_p2.read().is_01() || !tmp_4_cast_reg_974.read().is_01())? sc_lv<17>(): (sc_biguint<17>(tmp_50_fu_586_p2.read()) + sc_biguint<17>(tmp_4_cast_reg_974.read()));
}

void fc_layer1::thread_tmp_52_cast_fu_597_p1() {
    tmp_52_cast_fu_597_p1 = esl_zext<64,17>(tmp_51_fu_592_p2.read());
}

void fc_layer1::thread_tmp_52_fu_613_p3() {
    tmp_52_fu_613_p3 = esl_concat<7,9>(i_10_2_fu_602_p2.read(), ap_const_lv9_0);
}

void fc_layer1::thread_tmp_53_fu_625_p3() {
    tmp_53_fu_625_p3 = esl_concat<7,6>(i_10_2_fu_602_p2.read(), ap_const_lv6_0);
}

void fc_layer1::thread_tmp_54_fu_637_p2() {
    tmp_54_fu_637_p2 = (!p_shl3_cast_fu_633_p1.read().is_01() || !p_shl2_cast_fu_621_p1.read().is_01())? sc_lv<17>(): (sc_biguint<17>(p_shl3_cast_fu_633_p1.read()) + sc_biguint<17>(p_shl2_cast_fu_621_p1.read()));
}

void fc_layer1::thread_tmp_55_fu_643_p2() {
    tmp_55_fu_643_p2 = (!tmp_54_fu_637_p2.read().is_01() || !tmp_4_cast_reg_974.read().is_01())? sc_lv<17>(): (sc_biguint<17>(tmp_54_fu_637_p2.read()) + sc_biguint<17>(tmp_4_cast_reg_974.read()));
}

void fc_layer1::thread_tmp_56_cast_fu_648_p1() {
    tmp_56_cast_fu_648_p1 = esl_zext<64,17>(tmp_55_fu_643_p2.read());
}

void fc_layer1::thread_tmp_57_fu_698_p3() {
    tmp_57_fu_698_p3 = grp_fu_942_p3.read().range(43, 43);
}

void fc_layer1::thread_tmp_59_fu_725_p1() {
    tmp_59_fu_725_p1 = grp_fu_942_p3.read().range(27-1, 0);
}

void fc_layer1::thread_tmp_5_fu_679_p1() {
    tmp_5_fu_679_p1 = esl_zext<64,7>(i2_reg_320.read());
}

void fc_layer1::thread_tmp_60_fu_762_p3() {
    tmp_60_fu_762_p3 = p_Val2_13_fu_756_p2.read().range(16, 16);
}

void fc_layer1::thread_tmp_61_fu_786_p1() {
    tmp_61_fu_786_p1 = p_a_V_i_fu_770_p3.read().range(8-1, 0);
}

void fc_layer1::thread_tmp_7_fu_838_p2() {
    tmp_7_fu_838_p2 = (isneg_reg_1098.read() ^ ap_const_lv1_1);
}

void fc_layer1::thread_tmp_8_fu_441_p1() {
    tmp_8_fu_441_p1 = esl_zext<64,7>(i1_reg_308.read());
}

void fc_layer1::thread_tmp_s_fu_392_p1() {
    tmp_s_fu_392_p1 = esl_zext<64,7>(i_reg_284.read());
}

void fc_layer1::thread_underflow_fu_866_p2() {
    underflow_fu_866_p2 = (brmerge39_i_i_fu_860_p2.read() & isneg_reg_1098.read());
}

void fc_layer1::thread_underflow_not_fu_877_p2() {
    underflow_not_fu_877_p2 = (underflow_fu_866_p2.read() ^ ap_const_lv1_1);
}

void fc_layer1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((!(esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(exitcond5_fu_345_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 8 : 
            if ((!(esl_seteq<1,1,1>(exitcond6_fu_411_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(exitcond6_fu_411_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else if ((!(esl_seteq<1,1,1>(exitcond6_fu_411_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(exitcond6_fu_411_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(exitcond2_fu_435_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(exitcond_fu_667_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(out_V_V_full_n.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<12>) ("XXXXXXXXXXXX");
            break;
    }
}

}

