// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "fc_layer2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic fc_layer2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic fc_layer2::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<12> fc_layer2::ap_ST_fsm_state1 = "1";
const sc_lv<12> fc_layer2::ap_ST_fsm_state2 = "10";
const sc_lv<12> fc_layer2::ap_ST_fsm_state3 = "100";
const sc_lv<12> fc_layer2::ap_ST_fsm_state4 = "1000";
const sc_lv<12> fc_layer2::ap_ST_fsm_state5 = "10000";
const sc_lv<12> fc_layer2::ap_ST_fsm_state6 = "100000";
const sc_lv<12> fc_layer2::ap_ST_fsm_state7 = "1000000";
const sc_lv<12> fc_layer2::ap_ST_fsm_state8 = "10000000";
const sc_lv<12> fc_layer2::ap_ST_fsm_state9 = "100000000";
const sc_lv<12> fc_layer2::ap_ST_fsm_state10 = "1000000000";
const sc_lv<12> fc_layer2::ap_ST_fsm_state11 = "10000000000";
const sc_lv<12> fc_layer2::ap_ST_fsm_state12 = "100000000000";
const sc_lv<32> fc_layer2::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> fc_layer2::ap_const_lv32_B = "1011";
const sc_lv<32> fc_layer2::ap_const_lv32_3 = "11";
const sc_lv<1> fc_layer2::ap_const_lv1_0 = "0";
const sc_lv<32> fc_layer2::ap_const_lv32_1 = "1";
const sc_lv<32> fc_layer2::ap_const_lv32_4 = "100";
const sc_lv<1> fc_layer2::ap_const_lv1_1 = "1";
const sc_lv<32> fc_layer2::ap_const_lv32_5 = "101";
const sc_lv<32> fc_layer2::ap_const_lv32_6 = "110";
const sc_lv<32> fc_layer2::ap_const_lv32_8 = "1000";
const sc_lv<32> fc_layer2::ap_const_lv32_9 = "1001";
const sc_lv<32> fc_layer2::ap_const_lv32_A = "1010";
const sc_lv<7> fc_layer2::ap_const_lv7_0 = "0000000";
const sc_lv<32> fc_layer2::ap_const_lv32_2 = "10";
const sc_lv<7> fc_layer2::ap_const_lv7_1 = "1";
const sc_lv<32> fc_layer2::ap_const_lv32_7 = "111";
const sc_lv<64> fc_layer2::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<24> fc_layer2::ap_const_lv24_0 = "000000000000000000000000";
const sc_lv<9> fc_layer2::ap_const_lv9_2 = "10";
const sc_lv<7> fc_layer2::ap_const_lv7_54 = "1010100";
const sc_lv<3> fc_layer2::ap_const_lv3_0 = "000";
const sc_lv<7> fc_layer2::ap_const_lv7_78 = "1111000";
const sc_lv<7> fc_layer2::ap_const_lv7_2 = "10";
const sc_lv<7> fc_layer2::ap_const_lv7_3 = "11";
const sc_lv<7> fc_layer2::ap_const_lv7_4 = "100";
const sc_lv<43> fc_layer2::ap_const_lv43_7E211 = "1111110001000010001";
const sc_lv<32> fc_layer2::ap_const_lv32_2A = "101010";
const sc_lv<32> fc_layer2::ap_const_lv32_1C = "11100";
const sc_lv<32> fc_layer2::ap_const_lv32_1B = "11011";
const sc_lv<27> fc_layer2::ap_const_lv27_0 = "000000000000000000000000000";
const sc_lv<32> fc_layer2::ap_const_lv32_F = "1111";
const sc_lv<16> fc_layer2::ap_const_lv16_0 = "0000000000000000";
const sc_lv<24> fc_layer2::ap_const_lv24_FFFFFE = "111111111111111111111110";
const sc_lv<32> fc_layer2::ap_const_lv32_17 = "10111";
const sc_lv<8> fc_layer2::ap_const_lv8_FE = "11111110";
const sc_lv<16> fc_layer2::ap_const_lv16_FFFF = "1111111111111111";
const sc_lv<8> fc_layer2::ap_const_lv8_7F = "1111111";
const sc_lv<8> fc_layer2::ap_const_lv8_80 = "10000000";
const sc_lv<31> fc_layer2::ap_const_lv31_7E205 = "1111110001000000101";
const bool fc_layer2::ap_const_boolean_1 = true;

fc_layer2::fc_layer2(sc_module_name name) : sc_module(name), mVcdFile(0) {
    fc_layer2_weights_V_U = new fc_layer2_fc_layecbu("fc_layer2_weights_V_U");
    fc_layer2_weights_V_U->clk(ap_clk);
    fc_layer2_weights_V_U->reset(ap_rst);
    fc_layer2_weights_V_U->address0(fc_layer2_weights_V_address0);
    fc_layer2_weights_V_U->ce0(fc_layer2_weights_V_ce0);
    fc_layer2_weights_V_U->q0(fc_layer2_weights_V_q0);
    fc_layer2_weights_V_U->address1(fc_layer2_weights_V_address1);
    fc_layer2_weights_V_U->ce1(fc_layer2_weights_V_ce1);
    fc_layer2_weights_V_U->q1(fc_layer2_weights_V_q1);
    fc_layer2_bias_V_U = new fc_layer2_fc_layeccu("fc_layer2_bias_V_U");
    fc_layer2_bias_V_U->clk(ap_clk);
    fc_layer2_bias_V_U->reset(ap_rst);
    fc_layer2_bias_V_U->address0(fc_layer2_bias_V_address0);
    fc_layer2_bias_V_U->ce0(fc_layer2_bias_V_ce0);
    fc_layer2_bias_V_U->q0(fc_layer2_bias_V_q0);
    output_V_U = new fc_layer2_output_V("output_V_U");
    output_V_U->clk(ap_clk);
    output_V_U->reset(ap_rst);
    output_V_U->address0(output_V_address0);
    output_V_U->ce0(output_V_ce0);
    output_V_U->we0(output_V_we0);
    output_V_U->d0(output_V_d0);
    output_V_U->q0(output_V_q0);
    output_V_U->address1(output_V_address1);
    output_V_U->ce1(output_V_ce1);
    output_V_U->we1(output_V_we1);
    output_V_U->d1(output_V_d1);
    output_V_U->q1(output_V_q1);
    nnet_mac_muladd_8b9t_U68 = new nnet_mac_muladd_8b9t<1,1,8,9,24,24>("nnet_mac_muladd_8b9t_U68");
    nnet_mac_muladd_8b9t_U68->din0(fc_layer2_weights_V_q0);
    nnet_mac_muladd_8b9t_U68->din1(grp_fu_910_p1);
    nnet_mac_muladd_8b9t_U68->din2(output_V_q0);
    nnet_mac_muladd_8b9t_U68->dout(grp_fu_910_p3);
    nnet_mac_muladd_8b9t_U69 = new nnet_mac_muladd_8b9t<1,1,8,9,24,24>("nnet_mac_muladd_8b9t_U69");
    nnet_mac_muladd_8b9t_U69->din0(fc_layer2_weights_V_q1);
    nnet_mac_muladd_8b9t_U69->din1(grp_fu_917_p1);
    nnet_mac_muladd_8b9t_U69->din2(output_V_q1);
    nnet_mac_muladd_8b9t_U69->dout(grp_fu_917_p3);
    nnet_mac_muladd_8b9t_U70 = new nnet_mac_muladd_8b9t<1,1,8,9,24,24>("nnet_mac_muladd_8b9t_U70");
    nnet_mac_muladd_8b9t_U70->din0(fc_layer2_weights_V_q0);
    nnet_mac_muladd_8b9t_U70->din1(grp_fu_924_p1);
    nnet_mac_muladd_8b9t_U70->din2(output_V_q1);
    nnet_mac_muladd_8b9t_U70->dout(grp_fu_924_p3);
    nnet_mac_muladd_8b9t_U71 = new nnet_mac_muladd_8b9t<1,1,8,9,24,24>("nnet_mac_muladd_8b9t_U71");
    nnet_mac_muladd_8b9t_U71->din0(fc_layer2_weights_V_q1);
    nnet_mac_muladd_8b9t_U71->din1(grp_fu_931_p1);
    nnet_mac_muladd_8b9t_U71->din2(output_V_q0);
    nnet_mac_muladd_8b9t_U71->dout(grp_fu_931_p3);
    nnet_mac_muladd_3cdu_U72 = new nnet_mac_muladd_3cdu<1,1,31,11,43,43>("nnet_mac_muladd_3cdu_U72");
    nnet_mac_muladd_3cdu_U72->din0(ap_var_for_const0);
    nnet_mac_muladd_3cdu_U72->din1(f_op_V_2_reg_1084);
    nnet_mac_muladd_3cdu_U72->din2(p_Val2_s_reg_1079);
    nnet_mac_muladd_3cdu_U72->dout(grp_fu_938_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( in_V_V_empty_n );

    SC_METHOD(thread_ap_block_state4);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( exitcond4_fu_407_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( exitcond_fu_663_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( exitcond_fu_663_p2 );

    SC_METHOD(thread_brmerge39_i_i_fu_856_p2);
    sensitive << ( p_not38_i_i_fu_851_p2 );
    sensitive << ( newsignbit_0_not_i_i_fu_845_p2 );

    SC_METHOD(thread_brmerge_fu_879_p2);
    sensitive << ( overflow_fu_839_p2 );
    sensitive << ( underflow_not_fu_873_p2 );

    SC_METHOD(thread_brmerge_i_i_fu_828_p2);
    sensitive << ( newsignbit_fu_815_p3 );
    sensitive << ( p_not_i_i_fu_823_p2 );

    SC_METHOD(thread_brmerge_i_i_i_fu_867_p2);
    sensitive << ( underflow_fu_862_p2 );
    sensitive << ( overflow_fu_839_p2 );

    SC_METHOD(thread_exitcond1_fu_431_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i1_reg_304 );

    SC_METHOD(thread_exitcond3_fu_341_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_280 );

    SC_METHOD(thread_exitcond4_fu_407_p2);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond4_fu_407_p2 );
    sensitive << ( j_reg_292 );

    SC_METHOD(thread_exitcond_fu_663_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( i2_reg_316 );

    SC_METHOD(thread_fc_layer2_bias_V_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_6_fu_675_p1 );

    SC_METHOD(thread_fc_layer2_bias_V_ce0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_fc_layer2_weights_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_21_cast_fu_383_p1 );
    sensitive << ( tmp_25_cast_fu_477_p1 );
    sensitive << ( tmp_33_cast_fu_593_p1 );

    SC_METHOD(thread_fc_layer2_weights_V_address1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_29_cast_fu_528_p1 );
    sensitive << ( tmp_37_cast_fu_644_p1 );

    SC_METHOD(thread_fc_layer2_weights_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_fc_layer2_weights_V_ce1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_grp_fu_910_p1);
    sensitive << ( p_6_cast_reg_978 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_grp_fu_917_p1);
    sensitive << ( p_6_cast_reg_978 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_grp_fu_924_p1);
    sensitive << ( p_6_cast_reg_978 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_grp_fu_931_p1);
    sensitive << ( p_6_cast_reg_978 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_i_4_fu_347_p2);
    sensitive << ( i_reg_280 );

    SC_METHOD(thread_i_5_fu_669_p2);
    sensitive << ( i2_reg_316 );

    SC_METHOD(thread_i_7_1_fu_547_p2);
    sensitive << ( i1_reg_304 );

    SC_METHOD(thread_i_7_2_fu_598_p2);
    sensitive << ( i1_reg_304 );

    SC_METHOD(thread_i_7_3_fu_649_p2);
    sensitive << ( i1_reg_304 );

    SC_METHOD(thread_i_7_s_fu_482_p2);
    sensitive << ( i1_reg_304 );

    SC_METHOD(thread_in_V_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond4_fu_407_p2 );

    SC_METHOD(thread_in_V_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond4_fu_407_p2 );

    SC_METHOD(thread_j_2_fu_533_p2);
    sensitive << ( j_reg_292 );

    SC_METHOD(thread_lhs_V_2_fu_413_p1);
    sensitive << ( in_V_V_dout );

    SC_METHOD(thread_lhs_V_fu_327_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_V_V_dout );

    SC_METHOD(thread_lhs_V_fu_327_p1);
    sensitive << ( lhs_V_fu_327_p0 );

    SC_METHOD(thread_newsignbit_0_not_i_i_fu_845_p2);
    sensitive << ( newsignbit_fu_815_p3 );

    SC_METHOD(thread_newsignbit_fu_815_p3);
    sensitive << ( p_Val2_8_fu_810_p2 );

    SC_METHOD(thread_not_s_i_i2_fu_730_p2);
    sensitive << ( tmp_38_fu_694_p3 );

    SC_METHOD(thread_out_V_V_blk_n);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_out_V_V_din);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( brmerge_fu_879_p2 );
    sensitive << ( p_Val2_23_mux_fu_885_p3 );
    sensitive << ( p_Val2_s_518_fu_893_p3 );

    SC_METHOD(thread_out_V_V_write);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_output_V_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( output_V_addr_8_reg_1005 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( output_V_addr_10_reg_1041 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_s_fu_388_p1 );
    sensitive << ( tmp_2_fu_437_p1 );
    sensitive << ( tmp_76_3_fu_604_p1 );

    SC_METHOD(thread_output_V_address1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( output_V_addr_7_reg_994 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( output_V_addr_9_reg_1031 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_76_1_fu_488_p1 );
    sensitive << ( tmp_76_2_fu_553_p1 );
    sensitive << ( tmp_6_fu_675_p1 );

    SC_METHOD(thread_output_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_output_V_ce1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_output_V_d0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_77_1_reg_1021 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_77_3_reg_1056 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( p_5_cast_fu_402_p1 );

    SC_METHOD(thread_output_V_d1);
    sensitive << ( tmp_3_reg_1016 );
    sensitive << ( tmp_77_2_reg_1051 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_output_V_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_output_V_we1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_overflow_fu_839_p2);
    sensitive << ( brmerge_i_i_fu_828_p2 );
    sensitive << ( tmp_1_fu_834_p2 );

    SC_METHOD(thread_p_5_cast_fu_402_p1);
    sensitive << ( p_5_fu_397_p2 );

    SC_METHOD(thread_p_5_fu_397_p0);
    sensitive << ( fc_layer2_weights_V_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_p_5_fu_397_p1);
    sensitive << ( read_temp_V_cast_reg_949 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_p_5_fu_397_p2);
    sensitive << ( p_5_fu_397_p0 );
    sensitive << ( p_5_fu_397_p1 );

    SC_METHOD(thread_p_6_cast_fu_427_p1);
    sensitive << ( r_V_2_fu_417_p2 );

    SC_METHOD(thread_p_Val2_23_mux_fu_885_p3);
    sensitive << ( p_Val2_8_fu_810_p2 );
    sensitive << ( brmerge_i_i_i_fu_867_p2 );

    SC_METHOD(thread_p_Val2_6_fu_752_p2);
    sensitive << ( tmp_8_cast_fu_748_p1 );
    sensitive << ( p_Val2_7_cast_fu_710_p1 );

    SC_METHOD(thread_p_Val2_7_cast_fu_710_p1);
    sensitive << ( tmp_11_fu_701_p4 );

    SC_METHOD(thread_p_Val2_8_fu_810_p2);
    sensitive << ( tmp_42_reg_1089 );

    SC_METHOD(thread_p_Val2_s_518_fu_893_p3);
    sensitive << ( p_Val2_8_fu_810_p2 );
    sensitive << ( underflow_fu_862_p2 );

    SC_METHOD(thread_p_Val2_s_fu_685_p1);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( output_V_q1 );

    SC_METHOD(thread_p_Val2_s_fu_685_p2);
    sensitive << ( p_Val2_s_fu_685_p1 );

    SC_METHOD(thread_p_a_V_i_cast1_fu_774_p1);
    sensitive << ( p_a_V_i_fu_766_p3 );

    SC_METHOD(thread_p_a_V_i_cast_fu_778_p1);
    sensitive << ( p_a_V_i_cast1_fu_774_p1 );

    SC_METHOD(thread_p_a_V_i_fu_766_p3);
    sensitive << ( p_Val2_6_fu_752_p2 );
    sensitive << ( tmp_41_fu_758_p3 );

    SC_METHOD(thread_p_not38_i_i_fu_851_p2);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_12_reg_1100 );

    SC_METHOD(thread_p_not_i_i_fu_823_p2);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_12_reg_1100 );

    SC_METHOD(thread_p_shl1_cast_fu_373_p1);
    sensitive << ( tmp_19_fu_365_p3 );

    SC_METHOD(thread_p_shl2_cast_fu_617_p1);
    sensitive << ( tmp_33_fu_609_p3 );

    SC_METHOD(thread_p_shl3_cast_fu_629_p1);
    sensitive << ( tmp_34_fu_621_p3 );

    SC_METHOD(thread_p_shl4_cast_fu_566_p1);
    sensitive << ( tmp_29_fu_558_p3 );

    SC_METHOD(thread_p_shl5_cast_fu_578_p1);
    sensitive << ( tmp_30_fu_570_p3 );

    SC_METHOD(thread_p_shl6_cast_fu_501_p1);
    sensitive << ( tmp_25_fu_493_p3 );

    SC_METHOD(thread_p_shl7_cast_fu_513_p1);
    sensitive << ( tmp_26_fu_505_p3 );

    SC_METHOD(thread_p_shl8_cast_fu_450_p1);
    sensitive << ( tmp_21_fu_442_p3 );

    SC_METHOD(thread_p_shl9_cast_fu_462_p1);
    sensitive << ( tmp_22_fu_454_p3 );

    SC_METHOD(thread_p_shl_cast_fu_361_p1);
    sensitive << ( tmp_18_fu_353_p3 );

    SC_METHOD(thread_qb_assign_2_fu_742_p2);
    sensitive << ( r_i_i2_fu_736_p2 );
    sensitive << ( qbit_fu_714_p3 );

    SC_METHOD(thread_qbit_fu_714_p3);
    sensitive << ( grp_fu_938_p3 );

    SC_METHOD(thread_r_V_2_fu_417_p2);
    sensitive << ( lhs_V_2_fu_413_p1 );

    SC_METHOD(thread_r_V_4_fu_786_p2);
    sensitive << ( p_a_V_i_cast_fu_778_p1 );

    SC_METHOD(thread_r_V_fu_331_p2);
    sensitive << ( lhs_V_fu_327_p1 );

    SC_METHOD(thread_r_fu_724_p2);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( tmp_40_fu_721_p1 );

    SC_METHOD(thread_r_i_i2_fu_736_p2);
    sensitive << ( r_fu_724_p2 );
    sensitive << ( not_s_i_i2_fu_730_p2 );

    SC_METHOD(thread_read_temp_V_cast_fu_337_p1);
    sensitive << ( r_V_fu_331_p2 );

    SC_METHOD(thread_tmp_11_fu_701_p4);
    sensitive << ( grp_fu_938_p3 );

    SC_METHOD(thread_tmp_18_fu_353_p3);
    sensitive << ( i_reg_280 );

    SC_METHOD(thread_tmp_19_fu_365_p3);
    sensitive << ( i_reg_280 );

    SC_METHOD(thread_tmp_1_fu_834_p2);
    sensitive << ( isneg_reg_1094 );

    SC_METHOD(thread_tmp_20_fu_377_p2);
    sensitive << ( p_shl_cast_fu_361_p1 );
    sensitive << ( p_shl1_cast_fu_373_p1 );

    SC_METHOD(thread_tmp_21_cast_fu_383_p1);
    sensitive << ( tmp_20_fu_377_p2 );

    SC_METHOD(thread_tmp_21_fu_442_p3);
    sensitive << ( i1_reg_304 );

    SC_METHOD(thread_tmp_22_fu_454_p3);
    sensitive << ( i1_reg_304 );

    SC_METHOD(thread_tmp_23_fu_466_p2);
    sensitive << ( p_shl8_cast_fu_450_p1 );
    sensitive << ( p_shl9_cast_fu_462_p1 );

    SC_METHOD(thread_tmp_24_fu_472_p2);
    sensitive << ( tmp_5_cast_reg_970 );
    sensitive << ( tmp_23_fu_466_p2 );

    SC_METHOD(thread_tmp_25_cast_fu_477_p1);
    sensitive << ( tmp_24_fu_472_p2 );

    SC_METHOD(thread_tmp_25_fu_493_p3);
    sensitive << ( i_7_s_fu_482_p2 );

    SC_METHOD(thread_tmp_26_fu_505_p3);
    sensitive << ( i_7_s_fu_482_p2 );

    SC_METHOD(thread_tmp_27_fu_517_p2);
    sensitive << ( p_shl6_cast_fu_501_p1 );
    sensitive << ( p_shl7_cast_fu_513_p1 );

    SC_METHOD(thread_tmp_28_fu_523_p2);
    sensitive << ( tmp_5_cast_reg_970 );
    sensitive << ( tmp_27_fu_517_p2 );

    SC_METHOD(thread_tmp_29_cast_fu_528_p1);
    sensitive << ( tmp_28_fu_523_p2 );

    SC_METHOD(thread_tmp_29_fu_558_p3);
    sensitive << ( i_7_1_fu_547_p2 );

    SC_METHOD(thread_tmp_2_fu_437_p1);
    sensitive << ( i1_reg_304 );

    SC_METHOD(thread_tmp_30_fu_570_p3);
    sensitive << ( i_7_1_fu_547_p2 );

    SC_METHOD(thread_tmp_31_fu_582_p2);
    sensitive << ( p_shl4_cast_fu_566_p1 );
    sensitive << ( p_shl5_cast_fu_578_p1 );

    SC_METHOD(thread_tmp_32_fu_588_p2);
    sensitive << ( tmp_5_cast_reg_970 );
    sensitive << ( tmp_31_fu_582_p2 );

    SC_METHOD(thread_tmp_33_cast_fu_593_p1);
    sensitive << ( tmp_32_fu_588_p2 );

    SC_METHOD(thread_tmp_33_fu_609_p3);
    sensitive << ( i_7_2_fu_598_p2 );

    SC_METHOD(thread_tmp_34_fu_621_p3);
    sensitive << ( i_7_2_fu_598_p2 );

    SC_METHOD(thread_tmp_35_fu_633_p2);
    sensitive << ( p_shl2_cast_fu_617_p1 );
    sensitive << ( p_shl3_cast_fu_629_p1 );

    SC_METHOD(thread_tmp_36_fu_639_p2);
    sensitive << ( tmp_5_cast_reg_970 );
    sensitive << ( tmp_35_fu_633_p2 );

    SC_METHOD(thread_tmp_37_cast_fu_644_p1);
    sensitive << ( tmp_36_fu_639_p2 );

    SC_METHOD(thread_tmp_38_fu_694_p3);
    sensitive << ( grp_fu_938_p3 );

    SC_METHOD(thread_tmp_40_fu_721_p1);
    sensitive << ( grp_fu_938_p3 );

    SC_METHOD(thread_tmp_41_fu_758_p3);
    sensitive << ( p_Val2_6_fu_752_p2 );

    SC_METHOD(thread_tmp_42_fu_782_p1);
    sensitive << ( p_a_V_i_fu_766_p3 );

    SC_METHOD(thread_tmp_5_cast_fu_423_p1);
    sensitive << ( j_reg_292 );

    SC_METHOD(thread_tmp_6_fu_675_p1);
    sensitive << ( i2_reg_316 );

    SC_METHOD(thread_tmp_76_1_fu_488_p1);
    sensitive << ( i_7_s_fu_482_p2 );

    SC_METHOD(thread_tmp_76_2_fu_553_p1);
    sensitive << ( i_7_1_fu_547_p2 );

    SC_METHOD(thread_tmp_76_3_fu_604_p1);
    sensitive << ( i_7_2_fu_598_p2 );

    SC_METHOD(thread_tmp_8_cast_fu_748_p1);
    sensitive << ( qb_assign_2_fu_742_p2 );

    SC_METHOD(thread_tmp_s_fu_388_p1);
    sensitive << ( i_reg_280 );

    SC_METHOD(thread_underflow_fu_862_p2);
    sensitive << ( isneg_reg_1094 );
    sensitive << ( brmerge39_i_i_fu_856_p2 );

    SC_METHOD(thread_underflow_not_fu_873_p2);
    sensitive << ( underflow_fu_862_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( out_V_V_full_n );
    sensitive << ( in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond4_fu_407_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond3_fu_341_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( exitcond1_fu_431_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( exitcond_fu_663_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fc_layer2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, out_V_V_din, "(port)out_V_V_din");
    sc_trace(mVcdFile, out_V_V_full_n, "(port)out_V_V_full_n");
    sc_trace(mVcdFile, out_V_V_write, "(port)out_V_V_write");
    sc_trace(mVcdFile, in_V_V_dout, "(port)in_V_V_dout");
    sc_trace(mVcdFile, in_V_V_empty_n, "(port)in_V_V_empty_n");
    sc_trace(mVcdFile, in_V_V_read, "(port)in_V_V_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, fc_layer2_weights_V_address0, "fc_layer2_weights_V_address0");
    sc_trace(mVcdFile, fc_layer2_weights_V_ce0, "fc_layer2_weights_V_ce0");
    sc_trace(mVcdFile, fc_layer2_weights_V_q0, "fc_layer2_weights_V_q0");
    sc_trace(mVcdFile, fc_layer2_weights_V_address1, "fc_layer2_weights_V_address1");
    sc_trace(mVcdFile, fc_layer2_weights_V_ce1, "fc_layer2_weights_V_ce1");
    sc_trace(mVcdFile, fc_layer2_weights_V_q1, "fc_layer2_weights_V_q1");
    sc_trace(mVcdFile, fc_layer2_bias_V_address0, "fc_layer2_bias_V_address0");
    sc_trace(mVcdFile, fc_layer2_bias_V_ce0, "fc_layer2_bias_V_ce0");
    sc_trace(mVcdFile, fc_layer2_bias_V_q0, "fc_layer2_bias_V_q0");
    sc_trace(mVcdFile, out_V_V_blk_n, "out_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, in_V_V_blk_n, "in_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, exitcond4_fu_407_p2, "exitcond4_fu_407_p2");
    sc_trace(mVcdFile, read_temp_V_cast_fu_337_p1, "read_temp_V_cast_fu_337_p1");
    sc_trace(mVcdFile, read_temp_V_cast_reg_949, "read_temp_V_cast_reg_949");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, i_4_fu_347_p2, "i_4_fu_347_p2");
    sc_trace(mVcdFile, i_4_reg_957, "i_4_reg_957");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, exitcond3_fu_341_p2, "exitcond3_fu_341_p2");
    sc_trace(mVcdFile, tmp_5_cast_fu_423_p1, "tmp_5_cast_fu_423_p1");
    sc_trace(mVcdFile, tmp_5_cast_reg_970, "tmp_5_cast_reg_970");
    sc_trace(mVcdFile, ap_block_state4, "ap_block_state4");
    sc_trace(mVcdFile, p_6_cast_fu_427_p1, "p_6_cast_fu_427_p1");
    sc_trace(mVcdFile, p_6_cast_reg_978, "p_6_cast_reg_978");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, exitcond1_fu_431_p2, "exitcond1_fu_431_p2");
    sc_trace(mVcdFile, output_V_addr_7_reg_994, "output_V_addr_7_reg_994");
    sc_trace(mVcdFile, output_V_addr_8_reg_1005, "output_V_addr_8_reg_1005");
    sc_trace(mVcdFile, j_2_fu_533_p2, "j_2_fu_533_p2");
    sc_trace(mVcdFile, grp_fu_910_p3, "grp_fu_910_p3");
    sc_trace(mVcdFile, tmp_3_reg_1016, "tmp_3_reg_1016");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, grp_fu_917_p3, "grp_fu_917_p3");
    sc_trace(mVcdFile, tmp_77_1_reg_1021, "tmp_77_1_reg_1021");
    sc_trace(mVcdFile, output_V_addr_9_reg_1031, "output_V_addr_9_reg_1031");
    sc_trace(mVcdFile, output_V_addr_10_reg_1041, "output_V_addr_10_reg_1041");
    sc_trace(mVcdFile, i_7_3_fu_649_p2, "i_7_3_fu_649_p2");
    sc_trace(mVcdFile, i_7_3_reg_1046, "i_7_3_reg_1046");
    sc_trace(mVcdFile, grp_fu_924_p3, "grp_fu_924_p3");
    sc_trace(mVcdFile, tmp_77_2_reg_1051, "tmp_77_2_reg_1051");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, grp_fu_931_p3, "grp_fu_931_p3");
    sc_trace(mVcdFile, tmp_77_3_reg_1056, "tmp_77_3_reg_1056");
    sc_trace(mVcdFile, i_5_fu_669_p2, "i_5_fu_669_p2");
    sc_trace(mVcdFile, i_5_reg_1064, "i_5_reg_1064");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, exitcond_fu_663_p2, "exitcond_fu_663_p2");
    sc_trace(mVcdFile, p_Val2_s_fu_685_p2, "p_Val2_s_fu_685_p2");
    sc_trace(mVcdFile, p_Val2_s_reg_1079, "p_Val2_s_reg_1079");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, f_op_V_2_reg_1084, "f_op_V_2_reg_1084");
    sc_trace(mVcdFile, tmp_42_fu_782_p1, "tmp_42_fu_782_p1");
    sc_trace(mVcdFile, tmp_42_reg_1089, "tmp_42_reg_1089");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, isneg_reg_1094, "isneg_reg_1094");
    sc_trace(mVcdFile, tmp_12_reg_1100, "tmp_12_reg_1100");
    sc_trace(mVcdFile, output_V_address0, "output_V_address0");
    sc_trace(mVcdFile, output_V_ce0, "output_V_ce0");
    sc_trace(mVcdFile, output_V_we0, "output_V_we0");
    sc_trace(mVcdFile, output_V_d0, "output_V_d0");
    sc_trace(mVcdFile, output_V_q0, "output_V_q0");
    sc_trace(mVcdFile, output_V_address1, "output_V_address1");
    sc_trace(mVcdFile, output_V_ce1, "output_V_ce1");
    sc_trace(mVcdFile, output_V_we1, "output_V_we1");
    sc_trace(mVcdFile, output_V_d1, "output_V_d1");
    sc_trace(mVcdFile, output_V_q1, "output_V_q1");
    sc_trace(mVcdFile, i_reg_280, "i_reg_280");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, j_reg_292, "j_reg_292");
    sc_trace(mVcdFile, i1_reg_304, "i1_reg_304");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, i2_reg_316, "i2_reg_316");
    sc_trace(mVcdFile, tmp_21_cast_fu_383_p1, "tmp_21_cast_fu_383_p1");
    sc_trace(mVcdFile, tmp_s_fu_388_p1, "tmp_s_fu_388_p1");
    sc_trace(mVcdFile, tmp_25_cast_fu_477_p1, "tmp_25_cast_fu_477_p1");
    sc_trace(mVcdFile, tmp_2_fu_437_p1, "tmp_2_fu_437_p1");
    sc_trace(mVcdFile, tmp_29_cast_fu_528_p1, "tmp_29_cast_fu_528_p1");
    sc_trace(mVcdFile, tmp_76_1_fu_488_p1, "tmp_76_1_fu_488_p1");
    sc_trace(mVcdFile, tmp_33_cast_fu_593_p1, "tmp_33_cast_fu_593_p1");
    sc_trace(mVcdFile, tmp_76_2_fu_553_p1, "tmp_76_2_fu_553_p1");
    sc_trace(mVcdFile, tmp_37_cast_fu_644_p1, "tmp_37_cast_fu_644_p1");
    sc_trace(mVcdFile, tmp_76_3_fu_604_p1, "tmp_76_3_fu_604_p1");
    sc_trace(mVcdFile, tmp_6_fu_675_p1, "tmp_6_fu_675_p1");
    sc_trace(mVcdFile, p_5_cast_fu_402_p1, "p_5_cast_fu_402_p1");
    sc_trace(mVcdFile, lhs_V_fu_327_p0, "lhs_V_fu_327_p0");
    sc_trace(mVcdFile, lhs_V_fu_327_p1, "lhs_V_fu_327_p1");
    sc_trace(mVcdFile, r_V_fu_331_p2, "r_V_fu_331_p2");
    sc_trace(mVcdFile, tmp_18_fu_353_p3, "tmp_18_fu_353_p3");
    sc_trace(mVcdFile, tmp_19_fu_365_p3, "tmp_19_fu_365_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_361_p1, "p_shl_cast_fu_361_p1");
    sc_trace(mVcdFile, p_shl1_cast_fu_373_p1, "p_shl1_cast_fu_373_p1");
    sc_trace(mVcdFile, tmp_20_fu_377_p2, "tmp_20_fu_377_p2");
    sc_trace(mVcdFile, p_5_fu_397_p0, "p_5_fu_397_p0");
    sc_trace(mVcdFile, p_5_fu_397_p1, "p_5_fu_397_p1");
    sc_trace(mVcdFile, p_5_fu_397_p2, "p_5_fu_397_p2");
    sc_trace(mVcdFile, lhs_V_2_fu_413_p1, "lhs_V_2_fu_413_p1");
    sc_trace(mVcdFile, r_V_2_fu_417_p2, "r_V_2_fu_417_p2");
    sc_trace(mVcdFile, tmp_21_fu_442_p3, "tmp_21_fu_442_p3");
    sc_trace(mVcdFile, tmp_22_fu_454_p3, "tmp_22_fu_454_p3");
    sc_trace(mVcdFile, p_shl8_cast_fu_450_p1, "p_shl8_cast_fu_450_p1");
    sc_trace(mVcdFile, p_shl9_cast_fu_462_p1, "p_shl9_cast_fu_462_p1");
    sc_trace(mVcdFile, tmp_23_fu_466_p2, "tmp_23_fu_466_p2");
    sc_trace(mVcdFile, tmp_24_fu_472_p2, "tmp_24_fu_472_p2");
    sc_trace(mVcdFile, i_7_s_fu_482_p2, "i_7_s_fu_482_p2");
    sc_trace(mVcdFile, tmp_25_fu_493_p3, "tmp_25_fu_493_p3");
    sc_trace(mVcdFile, tmp_26_fu_505_p3, "tmp_26_fu_505_p3");
    sc_trace(mVcdFile, p_shl6_cast_fu_501_p1, "p_shl6_cast_fu_501_p1");
    sc_trace(mVcdFile, p_shl7_cast_fu_513_p1, "p_shl7_cast_fu_513_p1");
    sc_trace(mVcdFile, tmp_27_fu_517_p2, "tmp_27_fu_517_p2");
    sc_trace(mVcdFile, tmp_28_fu_523_p2, "tmp_28_fu_523_p2");
    sc_trace(mVcdFile, i_7_1_fu_547_p2, "i_7_1_fu_547_p2");
    sc_trace(mVcdFile, tmp_29_fu_558_p3, "tmp_29_fu_558_p3");
    sc_trace(mVcdFile, tmp_30_fu_570_p3, "tmp_30_fu_570_p3");
    sc_trace(mVcdFile, p_shl4_cast_fu_566_p1, "p_shl4_cast_fu_566_p1");
    sc_trace(mVcdFile, p_shl5_cast_fu_578_p1, "p_shl5_cast_fu_578_p1");
    sc_trace(mVcdFile, tmp_31_fu_582_p2, "tmp_31_fu_582_p2");
    sc_trace(mVcdFile, tmp_32_fu_588_p2, "tmp_32_fu_588_p2");
    sc_trace(mVcdFile, i_7_2_fu_598_p2, "i_7_2_fu_598_p2");
    sc_trace(mVcdFile, tmp_33_fu_609_p3, "tmp_33_fu_609_p3");
    sc_trace(mVcdFile, tmp_34_fu_621_p3, "tmp_34_fu_621_p3");
    sc_trace(mVcdFile, p_shl2_cast_fu_617_p1, "p_shl2_cast_fu_617_p1");
    sc_trace(mVcdFile, p_shl3_cast_fu_629_p1, "p_shl3_cast_fu_629_p1");
    sc_trace(mVcdFile, tmp_35_fu_633_p2, "tmp_35_fu_633_p2");
    sc_trace(mVcdFile, tmp_36_fu_639_p2, "tmp_36_fu_639_p2");
    sc_trace(mVcdFile, p_Val2_s_fu_685_p1, "p_Val2_s_fu_685_p1");
    sc_trace(mVcdFile, grp_fu_938_p3, "grp_fu_938_p3");
    sc_trace(mVcdFile, tmp_11_fu_701_p4, "tmp_11_fu_701_p4");
    sc_trace(mVcdFile, tmp_40_fu_721_p1, "tmp_40_fu_721_p1");
    sc_trace(mVcdFile, tmp_38_fu_694_p3, "tmp_38_fu_694_p3");
    sc_trace(mVcdFile, r_fu_724_p2, "r_fu_724_p2");
    sc_trace(mVcdFile, not_s_i_i2_fu_730_p2, "not_s_i_i2_fu_730_p2");
    sc_trace(mVcdFile, r_i_i2_fu_736_p2, "r_i_i2_fu_736_p2");
    sc_trace(mVcdFile, qbit_fu_714_p3, "qbit_fu_714_p3");
    sc_trace(mVcdFile, qb_assign_2_fu_742_p2, "qb_assign_2_fu_742_p2");
    sc_trace(mVcdFile, tmp_8_cast_fu_748_p1, "tmp_8_cast_fu_748_p1");
    sc_trace(mVcdFile, p_Val2_7_cast_fu_710_p1, "p_Val2_7_cast_fu_710_p1");
    sc_trace(mVcdFile, p_Val2_6_fu_752_p2, "p_Val2_6_fu_752_p2");
    sc_trace(mVcdFile, tmp_41_fu_758_p3, "tmp_41_fu_758_p3");
    sc_trace(mVcdFile, p_a_V_i_fu_766_p3, "p_a_V_i_fu_766_p3");
    sc_trace(mVcdFile, p_a_V_i_cast1_fu_774_p1, "p_a_V_i_cast1_fu_774_p1");
    sc_trace(mVcdFile, p_a_V_i_cast_fu_778_p1, "p_a_V_i_cast_fu_778_p1");
    sc_trace(mVcdFile, r_V_4_fu_786_p2, "r_V_4_fu_786_p2");
    sc_trace(mVcdFile, p_Val2_8_fu_810_p2, "p_Val2_8_fu_810_p2");
    sc_trace(mVcdFile, newsignbit_fu_815_p3, "newsignbit_fu_815_p3");
    sc_trace(mVcdFile, p_not_i_i_fu_823_p2, "p_not_i_i_fu_823_p2");
    sc_trace(mVcdFile, brmerge_i_i_fu_828_p2, "brmerge_i_i_fu_828_p2");
    sc_trace(mVcdFile, tmp_1_fu_834_p2, "tmp_1_fu_834_p2");
    sc_trace(mVcdFile, p_not38_i_i_fu_851_p2, "p_not38_i_i_fu_851_p2");
    sc_trace(mVcdFile, newsignbit_0_not_i_i_fu_845_p2, "newsignbit_0_not_i_i_fu_845_p2");
    sc_trace(mVcdFile, brmerge39_i_i_fu_856_p2, "brmerge39_i_i_fu_856_p2");
    sc_trace(mVcdFile, underflow_fu_862_p2, "underflow_fu_862_p2");
    sc_trace(mVcdFile, overflow_fu_839_p2, "overflow_fu_839_p2");
    sc_trace(mVcdFile, underflow_not_fu_873_p2, "underflow_not_fu_873_p2");
    sc_trace(mVcdFile, brmerge_i_i_i_fu_867_p2, "brmerge_i_i_i_fu_867_p2");
    sc_trace(mVcdFile, brmerge_fu_879_p2, "brmerge_fu_879_p2");
    sc_trace(mVcdFile, p_Val2_23_mux_fu_885_p3, "p_Val2_23_mux_fu_885_p3");
    sc_trace(mVcdFile, p_Val2_s_518_fu_893_p3, "p_Val2_s_518_fu_893_p3");
    sc_trace(mVcdFile, grp_fu_910_p1, "grp_fu_910_p1");
    sc_trace(mVcdFile, grp_fu_917_p1, "grp_fu_917_p1");
    sc_trace(mVcdFile, grp_fu_924_p1, "grp_fu_924_p1");
    sc_trace(mVcdFile, grp_fu_931_p1, "grp_fu_931_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

fc_layer2::~fc_layer2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete fc_layer2_weights_V_U;
    delete fc_layer2_bias_V_U;
    delete output_V_U;
    delete nnet_mac_muladd_8b9t_U68;
    delete nnet_mac_muladd_8b9t_U69;
    delete nnet_mac_muladd_8b9t_U70;
    delete nnet_mac_muladd_8b9t_U71;
    delete nnet_mac_muladd_3cdu_U72;
}

void fc_layer2::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv31_7E205;
}

void fc_layer2::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                    esl_seteq<1,1,1>(exitcond_fu_663_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i1_reg_304 = i_7_3_reg_1046.read();
    } else if ((!(esl_seteq<1,1,1>(exitcond4_fu_407_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0)) && 
                esl_seteq<1,1,1>(exitcond4_fu_407_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        i1_reg_304 = ap_const_lv7_0;
    }
    if ((!(esl_seteq<1,1,1>(exitcond4_fu_407_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0)) && 
         esl_seteq<1,1,1>(exitcond4_fu_407_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        i2_reg_316 = ap_const_lv7_0;
    } else if ((esl_seteq<1,1,1>(out_V_V_full_n.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        i2_reg_316 = i_5_reg_1064.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_reg_280 = i_4_reg_957.read();
    } else if ((!(esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        i_reg_280 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(exitcond3_fu_341_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        j_reg_292 = ap_const_lv7_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_431_p2.read(), ap_const_lv1_1))) {
        j_reg_292 = j_2_fu_533_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        f_op_V_2_reg_1084 = fc_layer2_bias_V_q0.read();
        p_Val2_s_reg_1079 = p_Val2_s_fu_685_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_4_reg_957 = i_4_fu_347_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        i_5_reg_1064 = i_5_fu_669_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_7_3_reg_1046 = i_7_3_fu_649_p2.read();
        output_V_addr_10_reg_1041 =  (sc_lv<7>) (tmp_76_3_fu_604_p1.read());
        output_V_addr_9_reg_1031 =  (sc_lv<7>) (tmp_76_2_fu_553_p1.read());
        tmp_3_reg_1016 = grp_fu_910_p3.read();
        tmp_77_1_reg_1021 = grp_fu_917_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        isneg_reg_1094 = r_V_4_fu_786_p2.read().range(23, 23);
        tmp_12_reg_1100 = r_V_4_fu_786_p2.read().range(23, 8);
        tmp_42_reg_1089 = tmp_42_fu_782_p1.read();
    }
    if ((esl_seteq<1,1,1>(exitcond1_fu_431_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        output_V_addr_7_reg_994 =  (sc_lv<7>) (tmp_2_fu_437_p1.read());
        output_V_addr_8_reg_1005 =  (sc_lv<7>) (tmp_76_1_fu_488_p1.read());
    }
    if ((!(esl_seteq<1,1,1>(exitcond4_fu_407_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(exitcond4_fu_407_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        p_6_cast_reg_978 = p_6_cast_fu_427_p1.read();
        tmp_5_cast_reg_970 = tmp_5_cast_fu_423_p1.read();
    }
    if ((!(esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        read_temp_V_cast_reg_949 = read_temp_V_cast_fu_337_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        tmp_77_2_reg_1051 = grp_fu_924_p3.read();
        tmp_77_3_reg_1056 = grp_fu_931_p3.read();
    }
}

void fc_layer2::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void fc_layer2::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void fc_layer2::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void fc_layer2::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void fc_layer2::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void fc_layer2::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void fc_layer2::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void fc_layer2::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void fc_layer2::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void fc_layer2::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void fc_layer2::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void fc_layer2::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void fc_layer2::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void fc_layer2::thread_ap_block_state4() {
    ap_block_state4 = (esl_seteq<1,1,1>(exitcond4_fu_407_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0));
}

void fc_layer2::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_663_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void fc_layer2::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void fc_layer2::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_663_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void fc_layer2::thread_brmerge39_i_i_fu_856_p2() {
    brmerge39_i_i_fu_856_p2 = (p_not38_i_i_fu_851_p2.read() | newsignbit_0_not_i_i_fu_845_p2.read());
}

void fc_layer2::thread_brmerge_fu_879_p2() {
    brmerge_fu_879_p2 = (overflow_fu_839_p2.read() | underflow_not_fu_873_p2.read());
}

void fc_layer2::thread_brmerge_i_i_fu_828_p2() {
    brmerge_i_i_fu_828_p2 = (newsignbit_fu_815_p3.read() | p_not_i_i_fu_823_p2.read());
}

void fc_layer2::thread_brmerge_i_i_i_fu_867_p2() {
    brmerge_i_i_i_fu_867_p2 = (underflow_fu_862_p2.read() | overflow_fu_839_p2.read());
}

void fc_layer2::thread_exitcond1_fu_431_p2() {
    exitcond1_fu_431_p2 = (!i1_reg_304.read().is_01() || !ap_const_lv7_54.is_01())? sc_lv<1>(): sc_lv<1>(i1_reg_304.read() == ap_const_lv7_54);
}

void fc_layer2::thread_exitcond3_fu_341_p2() {
    exitcond3_fu_341_p2 = (!i_reg_280.read().is_01() || !ap_const_lv7_54.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_280.read() == ap_const_lv7_54);
}

void fc_layer2::thread_exitcond4_fu_407_p2() {
    exitcond4_fu_407_p2 = (!j_reg_292.read().is_01() || !ap_const_lv7_78.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_292.read() == ap_const_lv7_78);
}

void fc_layer2::thread_exitcond_fu_663_p2() {
    exitcond_fu_663_p2 = (!i2_reg_316.read().is_01() || !ap_const_lv7_54.is_01())? sc_lv<1>(): sc_lv<1>(i2_reg_316.read() == ap_const_lv7_54);
}

void fc_layer2::thread_fc_layer2_bias_V_address0() {
    fc_layer2_bias_V_address0 =  (sc_lv<7>) (tmp_6_fu_675_p1.read());
}

void fc_layer2::thread_fc_layer2_bias_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        fc_layer2_bias_V_ce0 = ap_const_logic_1;
    } else {
        fc_layer2_bias_V_ce0 = ap_const_logic_0;
    }
}

void fc_layer2::thread_fc_layer2_weights_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        fc_layer2_weights_V_address0 =  (sc_lv<14>) (tmp_33_cast_fu_593_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        fc_layer2_weights_V_address0 =  (sc_lv<14>) (tmp_25_cast_fu_477_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        fc_layer2_weights_V_address0 =  (sc_lv<14>) (tmp_21_cast_fu_383_p1.read());
    } else {
        fc_layer2_weights_V_address0 = "XXXXXXXXXXXXXX";
    }
}

void fc_layer2::thread_fc_layer2_weights_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        fc_layer2_weights_V_address1 =  (sc_lv<14>) (tmp_37_cast_fu_644_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        fc_layer2_weights_V_address1 =  (sc_lv<14>) (tmp_29_cast_fu_528_p1.read());
    } else {
        fc_layer2_weights_V_address1 = "XXXXXXXXXXXXXX";
    }
}

void fc_layer2::thread_fc_layer2_weights_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        fc_layer2_weights_V_ce0 = ap_const_logic_1;
    } else {
        fc_layer2_weights_V_ce0 = ap_const_logic_0;
    }
}

void fc_layer2::thread_fc_layer2_weights_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        fc_layer2_weights_V_ce1 = ap_const_logic_1;
    } else {
        fc_layer2_weights_V_ce1 = ap_const_logic_0;
    }
}

void fc_layer2::thread_grp_fu_910_p1() {
    grp_fu_910_p1 =  (sc_lv<9>) (p_6_cast_reg_978.read());
}

void fc_layer2::thread_grp_fu_917_p1() {
    grp_fu_917_p1 =  (sc_lv<9>) (p_6_cast_reg_978.read());
}

void fc_layer2::thread_grp_fu_924_p1() {
    grp_fu_924_p1 =  (sc_lv<9>) (p_6_cast_reg_978.read());
}

void fc_layer2::thread_grp_fu_931_p1() {
    grp_fu_931_p1 =  (sc_lv<9>) (p_6_cast_reg_978.read());
}

void fc_layer2::thread_i_4_fu_347_p2() {
    i_4_fu_347_p2 = (!i_reg_280.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i_reg_280.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void fc_layer2::thread_i_5_fu_669_p2() {
    i_5_fu_669_p2 = (!i2_reg_316.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i2_reg_316.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void fc_layer2::thread_i_7_1_fu_547_p2() {
    i_7_1_fu_547_p2 = (i1_reg_304.read() | ap_const_lv7_2);
}

void fc_layer2::thread_i_7_2_fu_598_p2() {
    i_7_2_fu_598_p2 = (i1_reg_304.read() | ap_const_lv7_3);
}

void fc_layer2::thread_i_7_3_fu_649_p2() {
    i_7_3_fu_649_p2 = (!i1_reg_304.read().is_01() || !ap_const_lv7_4.is_01())? sc_lv<7>(): (sc_biguint<7>(i1_reg_304.read()) + sc_biguint<7>(ap_const_lv7_4));
}

void fc_layer2::thread_i_7_s_fu_482_p2() {
    i_7_s_fu_482_p2 = (i1_reg_304.read() | ap_const_lv7_1);
}

void fc_layer2::thread_in_V_V_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(exitcond4_fu_407_p2.read(), ap_const_lv1_0)))) {
        in_V_V_blk_n = in_V_V_empty_n.read();
    } else {
        in_V_V_blk_n = ap_const_logic_1;
    }
}

void fc_layer2::thread_in_V_V_read() {
    if (((!(esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (!(esl_seteq<1,1,1>(exitcond4_fu_407_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(exitcond4_fu_407_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())))) {
        in_V_V_read = ap_const_logic_1;
    } else {
        in_V_V_read = ap_const_logic_0;
    }
}

void fc_layer2::thread_j_2_fu_533_p2() {
    j_2_fu_533_p2 = (!j_reg_292.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(j_reg_292.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void fc_layer2::thread_lhs_V_2_fu_413_p1() {
    lhs_V_2_fu_413_p1 = esl_sext<9,8>(in_V_V_dout.read());
}

void fc_layer2::thread_lhs_V_fu_327_p0() {
    lhs_V_fu_327_p0 = in_V_V_dout.read();
}

void fc_layer2::thread_lhs_V_fu_327_p1() {
    lhs_V_fu_327_p1 = esl_sext<9,8>(lhs_V_fu_327_p0.read());
}

void fc_layer2::thread_newsignbit_0_not_i_i_fu_845_p2() {
    newsignbit_0_not_i_i_fu_845_p2 = (newsignbit_fu_815_p3.read() ^ ap_const_lv1_1);
}

void fc_layer2::thread_newsignbit_fu_815_p3() {
    newsignbit_fu_815_p3 = p_Val2_8_fu_810_p2.read().range(7, 7);
}

void fc_layer2::thread_not_s_i_i2_fu_730_p2() {
    not_s_i_i2_fu_730_p2 = (tmp_38_fu_694_p3.read() ^ ap_const_lv1_1);
}

void fc_layer2::thread_out_V_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        out_V_V_blk_n = out_V_V_full_n.read();
    } else {
        out_V_V_blk_n = ap_const_logic_1;
    }
}

void fc_layer2::thread_out_V_V_din() {
    out_V_V_din = (!brmerge_fu_879_p2.read()[0].is_01())? sc_lv<8>(): ((brmerge_fu_879_p2.read()[0].to_bool())? p_Val2_23_mux_fu_885_p3.read(): p_Val2_s_518_fu_893_p3.read());
}

void fc_layer2::thread_out_V_V_write() {
    if ((esl_seteq<1,1,1>(out_V_V_full_n.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        out_V_V_write = ap_const_logic_1;
    } else {
        out_V_V_write = ap_const_logic_0;
    }
}

void fc_layer2::thread_output_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        output_V_address0 = output_V_addr_10_reg_1041.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_V_address0 = output_V_addr_8_reg_1005.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_V_address0 =  (sc_lv<7>) (tmp_76_3_fu_604_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        output_V_address0 =  (sc_lv<7>) (tmp_2_fu_437_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        output_V_address0 =  (sc_lv<7>) (tmp_s_fu_388_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        output_V_address0 =  (sc_lv<7>) (ap_const_lv64_0);
    } else {
        output_V_address0 =  (sc_lv<7>) ("XXXXXXX");
    }
}

void fc_layer2::thread_output_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        output_V_address1 =  (sc_lv<7>) (tmp_6_fu_675_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        output_V_address1 = output_V_addr_9_reg_1031.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_V_address1 = output_V_addr_7_reg_994.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_V_address1 =  (sc_lv<7>) (tmp_76_2_fu_553_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        output_V_address1 =  (sc_lv<7>) (tmp_76_1_fu_488_p1.read());
    } else {
        output_V_address1 =  (sc_lv<7>) ("XXXXXXX");
    }
}

void fc_layer2::thread_output_V_ce0() {
    if (((!(esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        output_V_ce0 = ap_const_logic_1;
    } else {
        output_V_ce0 = ap_const_logic_0;
    }
}

void fc_layer2::thread_output_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        output_V_ce1 = ap_const_logic_1;
    } else {
        output_V_ce1 = ap_const_logic_0;
    }
}

void fc_layer2::thread_output_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        output_V_d0 = tmp_77_3_reg_1056.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_V_d0 = tmp_77_1_reg_1021.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        output_V_d0 = p_5_cast_fu_402_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        output_V_d0 = ap_const_lv24_0;
    } else {
        output_V_d0 =  (sc_lv<24>) ("XXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fc_layer2::thread_output_V_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        output_V_d1 = tmp_77_2_reg_1051.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_V_d1 = tmp_3_reg_1016.read();
    } else {
        output_V_d1 =  (sc_lv<24>) ("XXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fc_layer2::thread_output_V_we0() {
    if (((!(esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        output_V_we0 = ap_const_logic_1;
    } else {
        output_V_we0 = ap_const_logic_0;
    }
}

void fc_layer2::thread_output_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        output_V_we1 = ap_const_logic_1;
    } else {
        output_V_we1 = ap_const_logic_0;
    }
}

void fc_layer2::thread_overflow_fu_839_p2() {
    overflow_fu_839_p2 = (brmerge_i_i_fu_828_p2.read() & tmp_1_fu_834_p2.read());
}

void fc_layer2::thread_p_5_cast_fu_402_p1() {
    p_5_cast_fu_402_p1 = esl_sext<24,17>(p_5_fu_397_p2.read());
}

void fc_layer2::thread_p_5_fu_397_p0() {
    p_5_fu_397_p0 = fc_layer2_weights_V_q0.read();
}

void fc_layer2::thread_p_5_fu_397_p1() {
    p_5_fu_397_p1 =  (sc_lv<9>) (read_temp_V_cast_reg_949.read());
}

void fc_layer2::thread_p_5_fu_397_p2() {
    p_5_fu_397_p2 = (!p_5_fu_397_p0.read().is_01() || !p_5_fu_397_p1.read().is_01())? sc_lv<17>(): sc_bigint<8>(p_5_fu_397_p0.read()) * sc_bigint<9>(p_5_fu_397_p1.read());
}

void fc_layer2::thread_p_6_cast_fu_427_p1() {
    p_6_cast_fu_427_p1 = esl_sext<17,9>(r_V_2_fu_417_p2.read());
}

void fc_layer2::thread_p_Val2_23_mux_fu_885_p3() {
    p_Val2_23_mux_fu_885_p3 = (!brmerge_i_i_i_fu_867_p2.read()[0].is_01())? sc_lv<8>(): ((brmerge_i_i_i_fu_867_p2.read()[0].to_bool())? ap_const_lv8_7F: p_Val2_8_fu_810_p2.read());
}

void fc_layer2::thread_p_Val2_6_fu_752_p2() {
    p_Val2_6_fu_752_p2 = (!tmp_8_cast_fu_748_p1.read().is_01() || !p_Val2_7_cast_fu_710_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_8_cast_fu_748_p1.read()) + sc_bigint<16>(p_Val2_7_cast_fu_710_p1.read()));
}

void fc_layer2::thread_p_Val2_7_cast_fu_710_p1() {
    p_Val2_7_cast_fu_710_p1 = esl_sext<16,15>(tmp_11_fu_701_p4.read());
}

void fc_layer2::thread_p_Val2_8_fu_810_p2() {
    p_Val2_8_fu_810_p2 = (!ap_const_lv8_FE.is_01() || !tmp_42_reg_1089.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_FE) + sc_biguint<8>(tmp_42_reg_1089.read()));
}

void fc_layer2::thread_p_Val2_s_518_fu_893_p3() {
    p_Val2_s_518_fu_893_p3 = (!underflow_fu_862_p2.read()[0].is_01())? sc_lv<8>(): ((underflow_fu_862_p2.read()[0].to_bool())? ap_const_lv8_80: p_Val2_8_fu_810_p2.read());
}

void fc_layer2::thread_p_Val2_s_fu_685_p1() {
    p_Val2_s_fu_685_p1 = output_V_q1.read();
}

void fc_layer2::thread_p_Val2_s_fu_685_p2() {
    p_Val2_s_fu_685_p2 = (!ap_const_lv43_7E211.is_01() || !p_Val2_s_fu_685_p1.read().is_01())? sc_lv<43>(): sc_biguint<43>(ap_const_lv43_7E211) * sc_bigint<24>(p_Val2_s_fu_685_p1.read());
}

void fc_layer2::thread_p_a_V_i_cast1_fu_774_p1() {
    p_a_V_i_cast1_fu_774_p1 = esl_sext<23,16>(p_a_V_i_fu_766_p3.read());
}

void fc_layer2::thread_p_a_V_i_cast_fu_778_p1() {
    p_a_V_i_cast_fu_778_p1 = esl_zext<24,23>(p_a_V_i_cast1_fu_774_p1.read());
}

void fc_layer2::thread_p_a_V_i_fu_766_p3() {
    p_a_V_i_fu_766_p3 = (!tmp_41_fu_758_p3.read()[0].is_01())? sc_lv<16>(): ((tmp_41_fu_758_p3.read()[0].to_bool())? ap_const_lv16_0: p_Val2_6_fu_752_p2.read());
}

void fc_layer2::thread_p_not38_i_i_fu_851_p2() {
    p_not38_i_i_fu_851_p2 = (!tmp_12_reg_1100.read().is_01() || !ap_const_lv16_FFFF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_12_reg_1100.read() != ap_const_lv16_FFFF);
}

void fc_layer2::thread_p_not_i_i_fu_823_p2() {
    p_not_i_i_fu_823_p2 = (!tmp_12_reg_1100.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_12_reg_1100.read() != ap_const_lv16_0);
}

void fc_layer2::thread_p_shl1_cast_fu_373_p1() {
    p_shl1_cast_fu_373_p1 = esl_zext<15,10>(tmp_19_fu_365_p3.read());
}

void fc_layer2::thread_p_shl2_cast_fu_617_p1() {
    p_shl2_cast_fu_617_p1 = esl_zext<15,14>(tmp_33_fu_609_p3.read());
}

void fc_layer2::thread_p_shl3_cast_fu_629_p1() {
    p_shl3_cast_fu_629_p1 = esl_zext<15,10>(tmp_34_fu_621_p3.read());
}

void fc_layer2::thread_p_shl4_cast_fu_566_p1() {
    p_shl4_cast_fu_566_p1 = esl_zext<15,14>(tmp_29_fu_558_p3.read());
}

void fc_layer2::thread_p_shl5_cast_fu_578_p1() {
    p_shl5_cast_fu_578_p1 = esl_zext<15,10>(tmp_30_fu_570_p3.read());
}

void fc_layer2::thread_p_shl6_cast_fu_501_p1() {
    p_shl6_cast_fu_501_p1 = esl_zext<15,14>(tmp_25_fu_493_p3.read());
}

void fc_layer2::thread_p_shl7_cast_fu_513_p1() {
    p_shl7_cast_fu_513_p1 = esl_zext<15,10>(tmp_26_fu_505_p3.read());
}

void fc_layer2::thread_p_shl8_cast_fu_450_p1() {
    p_shl8_cast_fu_450_p1 = esl_zext<15,14>(tmp_21_fu_442_p3.read());
}

void fc_layer2::thread_p_shl9_cast_fu_462_p1() {
    p_shl9_cast_fu_462_p1 = esl_zext<15,10>(tmp_22_fu_454_p3.read());
}

void fc_layer2::thread_p_shl_cast_fu_361_p1() {
    p_shl_cast_fu_361_p1 = esl_zext<15,14>(tmp_18_fu_353_p3.read());
}

void fc_layer2::thread_qb_assign_2_fu_742_p2() {
    qb_assign_2_fu_742_p2 = (r_i_i2_fu_736_p2.read() & qbit_fu_714_p3.read());
}

void fc_layer2::thread_qbit_fu_714_p3() {
    qbit_fu_714_p3 = grp_fu_938_p3.read().range(27, 27);
}

void fc_layer2::thread_r_V_2_fu_417_p2() {
    r_V_2_fu_417_p2 = (!lhs_V_2_fu_413_p1.read().is_01() || !ap_const_lv9_2.is_01())? sc_lv<9>(): (sc_bigint<9>(lhs_V_2_fu_413_p1.read()) + sc_biguint<9>(ap_const_lv9_2));
}

void fc_layer2::thread_r_V_4_fu_786_p2() {
    r_V_4_fu_786_p2 = (!ap_const_lv24_FFFFFE.is_01() || !p_a_V_i_cast_fu_778_p1.read().is_01())? sc_lv<24>(): (sc_bigint<24>(ap_const_lv24_FFFFFE) + sc_biguint<24>(p_a_V_i_cast_fu_778_p1.read()));
}

void fc_layer2::thread_r_V_fu_331_p2() {
    r_V_fu_331_p2 = (!lhs_V_fu_327_p1.read().is_01() || !ap_const_lv9_2.is_01())? sc_lv<9>(): (sc_bigint<9>(lhs_V_fu_327_p1.read()) + sc_biguint<9>(ap_const_lv9_2));
}

void fc_layer2::thread_r_fu_724_p2() {
    r_fu_724_p2 = (!tmp_40_fu_721_p1.read().is_01() || !ap_const_lv27_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_40_fu_721_p1.read() != ap_const_lv27_0);
}

void fc_layer2::thread_r_i_i2_fu_736_p2() {
    r_i_i2_fu_736_p2 = (r_fu_724_p2.read() | not_s_i_i2_fu_730_p2.read());
}

void fc_layer2::thread_read_temp_V_cast_fu_337_p1() {
    read_temp_V_cast_fu_337_p1 = esl_sext<17,9>(r_V_fu_331_p2.read());
}

void fc_layer2::thread_tmp_11_fu_701_p4() {
    tmp_11_fu_701_p4 = grp_fu_938_p3.read().range(42, 28);
}

void fc_layer2::thread_tmp_18_fu_353_p3() {
    tmp_18_fu_353_p3 = esl_concat<7,7>(i_reg_280.read(), ap_const_lv7_0);
}

void fc_layer2::thread_tmp_19_fu_365_p3() {
    tmp_19_fu_365_p3 = esl_concat<7,3>(i_reg_280.read(), ap_const_lv3_0);
}

void fc_layer2::thread_tmp_1_fu_834_p2() {
    tmp_1_fu_834_p2 = (isneg_reg_1094.read() ^ ap_const_lv1_1);
}

void fc_layer2::thread_tmp_20_fu_377_p2() {
    tmp_20_fu_377_p2 = (!p_shl_cast_fu_361_p1.read().is_01() || !p_shl1_cast_fu_373_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_shl_cast_fu_361_p1.read()) - sc_biguint<15>(p_shl1_cast_fu_373_p1.read()));
}

void fc_layer2::thread_tmp_21_cast_fu_383_p1() {
    tmp_21_cast_fu_383_p1 = esl_sext<64,15>(tmp_20_fu_377_p2.read());
}

void fc_layer2::thread_tmp_21_fu_442_p3() {
    tmp_21_fu_442_p3 = esl_concat<7,7>(i1_reg_304.read(), ap_const_lv7_0);
}

void fc_layer2::thread_tmp_22_fu_454_p3() {
    tmp_22_fu_454_p3 = esl_concat<7,3>(i1_reg_304.read(), ap_const_lv3_0);
}

void fc_layer2::thread_tmp_23_fu_466_p2() {
    tmp_23_fu_466_p2 = (!p_shl8_cast_fu_450_p1.read().is_01() || !p_shl9_cast_fu_462_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_shl8_cast_fu_450_p1.read()) - sc_biguint<15>(p_shl9_cast_fu_462_p1.read()));
}

void fc_layer2::thread_tmp_24_fu_472_p2() {
    tmp_24_fu_472_p2 = (!tmp_23_fu_466_p2.read().is_01() || !tmp_5_cast_reg_970.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_23_fu_466_p2.read()) + sc_biguint<15>(tmp_5_cast_reg_970.read()));
}

void fc_layer2::thread_tmp_25_cast_fu_477_p1() {
    tmp_25_cast_fu_477_p1 = esl_sext<64,15>(tmp_24_fu_472_p2.read());
}

void fc_layer2::thread_tmp_25_fu_493_p3() {
    tmp_25_fu_493_p3 = esl_concat<7,7>(i_7_s_fu_482_p2.read(), ap_const_lv7_0);
}

void fc_layer2::thread_tmp_26_fu_505_p3() {
    tmp_26_fu_505_p3 = esl_concat<7,3>(i_7_s_fu_482_p2.read(), ap_const_lv3_0);
}

void fc_layer2::thread_tmp_27_fu_517_p2() {
    tmp_27_fu_517_p2 = (!p_shl6_cast_fu_501_p1.read().is_01() || !p_shl7_cast_fu_513_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_shl6_cast_fu_501_p1.read()) - sc_biguint<15>(p_shl7_cast_fu_513_p1.read()));
}

void fc_layer2::thread_tmp_28_fu_523_p2() {
    tmp_28_fu_523_p2 = (!tmp_27_fu_517_p2.read().is_01() || !tmp_5_cast_reg_970.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_27_fu_517_p2.read()) + sc_biguint<15>(tmp_5_cast_reg_970.read()));
}

void fc_layer2::thread_tmp_29_cast_fu_528_p1() {
    tmp_29_cast_fu_528_p1 = esl_sext<64,15>(tmp_28_fu_523_p2.read());
}

void fc_layer2::thread_tmp_29_fu_558_p3() {
    tmp_29_fu_558_p3 = esl_concat<7,7>(i_7_1_fu_547_p2.read(), ap_const_lv7_0);
}

void fc_layer2::thread_tmp_2_fu_437_p1() {
    tmp_2_fu_437_p1 = esl_zext<64,7>(i1_reg_304.read());
}

void fc_layer2::thread_tmp_30_fu_570_p3() {
    tmp_30_fu_570_p3 = esl_concat<7,3>(i_7_1_fu_547_p2.read(), ap_const_lv3_0);
}

void fc_layer2::thread_tmp_31_fu_582_p2() {
    tmp_31_fu_582_p2 = (!p_shl4_cast_fu_566_p1.read().is_01() || !p_shl5_cast_fu_578_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_shl4_cast_fu_566_p1.read()) - sc_biguint<15>(p_shl5_cast_fu_578_p1.read()));
}

void fc_layer2::thread_tmp_32_fu_588_p2() {
    tmp_32_fu_588_p2 = (!tmp_31_fu_582_p2.read().is_01() || !tmp_5_cast_reg_970.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_31_fu_582_p2.read()) + sc_biguint<15>(tmp_5_cast_reg_970.read()));
}

void fc_layer2::thread_tmp_33_cast_fu_593_p1() {
    tmp_33_cast_fu_593_p1 = esl_sext<64,15>(tmp_32_fu_588_p2.read());
}

void fc_layer2::thread_tmp_33_fu_609_p3() {
    tmp_33_fu_609_p3 = esl_concat<7,7>(i_7_2_fu_598_p2.read(), ap_const_lv7_0);
}

void fc_layer2::thread_tmp_34_fu_621_p3() {
    tmp_34_fu_621_p3 = esl_concat<7,3>(i_7_2_fu_598_p2.read(), ap_const_lv3_0);
}

void fc_layer2::thread_tmp_35_fu_633_p2() {
    tmp_35_fu_633_p2 = (!p_shl2_cast_fu_617_p1.read().is_01() || !p_shl3_cast_fu_629_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_shl2_cast_fu_617_p1.read()) - sc_biguint<15>(p_shl3_cast_fu_629_p1.read()));
}

void fc_layer2::thread_tmp_36_fu_639_p2() {
    tmp_36_fu_639_p2 = (!tmp_35_fu_633_p2.read().is_01() || !tmp_5_cast_reg_970.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_35_fu_633_p2.read()) + sc_biguint<15>(tmp_5_cast_reg_970.read()));
}

void fc_layer2::thread_tmp_37_cast_fu_644_p1() {
    tmp_37_cast_fu_644_p1 = esl_sext<64,15>(tmp_36_fu_639_p2.read());
}

void fc_layer2::thread_tmp_38_fu_694_p3() {
    tmp_38_fu_694_p3 = grp_fu_938_p3.read().range(42, 42);
}

void fc_layer2::thread_tmp_40_fu_721_p1() {
    tmp_40_fu_721_p1 = grp_fu_938_p3.read().range(27-1, 0);
}

void fc_layer2::thread_tmp_41_fu_758_p3() {
    tmp_41_fu_758_p3 = p_Val2_6_fu_752_p2.read().range(15, 15);
}

void fc_layer2::thread_tmp_42_fu_782_p1() {
    tmp_42_fu_782_p1 = p_a_V_i_fu_766_p3.read().range(8-1, 0);
}

void fc_layer2::thread_tmp_5_cast_fu_423_p1() {
    tmp_5_cast_fu_423_p1 = esl_zext<15,7>(j_reg_292.read());
}

void fc_layer2::thread_tmp_6_fu_675_p1() {
    tmp_6_fu_675_p1 = esl_zext<64,7>(i2_reg_316.read());
}

void fc_layer2::thread_tmp_76_1_fu_488_p1() {
    tmp_76_1_fu_488_p1 = esl_zext<64,7>(i_7_s_fu_482_p2.read());
}

void fc_layer2::thread_tmp_76_2_fu_553_p1() {
    tmp_76_2_fu_553_p1 = esl_zext<64,7>(i_7_1_fu_547_p2.read());
}

void fc_layer2::thread_tmp_76_3_fu_604_p1() {
    tmp_76_3_fu_604_p1 = esl_zext<64,7>(i_7_2_fu_598_p2.read());
}

void fc_layer2::thread_tmp_8_cast_fu_748_p1() {
    tmp_8_cast_fu_748_p1 = esl_zext<16,1>(qb_assign_2_fu_742_p2.read());
}

void fc_layer2::thread_tmp_s_fu_388_p1() {
    tmp_s_fu_388_p1 = esl_zext<64,7>(i_reg_280.read());
}

void fc_layer2::thread_underflow_fu_862_p2() {
    underflow_fu_862_p2 = (brmerge39_i_i_fu_856_p2.read() & isneg_reg_1094.read());
}

void fc_layer2::thread_underflow_not_fu_873_p2() {
    underflow_not_fu_873_p2 = (underflow_fu_862_p2.read() ^ ap_const_lv1_1);
}

void fc_layer2::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((!(esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(exitcond3_fu_341_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 8 : 
            if ((!(esl_seteq<1,1,1>(exitcond4_fu_407_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(exitcond4_fu_407_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else if ((!(esl_seteq<1,1,1>(exitcond4_fu_407_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(in_V_V_empty_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(exitcond4_fu_407_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(exitcond1_fu_431_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(exitcond_fu_663_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(out_V_V_full_n.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<12>) ("XXXXXXXXXXXX");
            break;
    }
}

}

