// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Loop_1_proc181_HH_
#define _Loop_1_proc181_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Loop_1_proc181_inbkb.h"

namespace ap_rtl {

struct Loop_1_proc181 : public sc_module {
    // Port declarations 10
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<8> > image_in_V_V_din;
    sc_in< sc_logic > image_in_V_V_full_n;
    sc_out< sc_logic > image_in_V_V_write;


    // Module declarations
    Loop_1_proc181(sc_module_name name);
    SC_HAS_PROCESS(Loop_1_proc181);

    ~Loop_1_proc181();

    sc_trace_file* mVcdFile;

    Loop_1_proc181_inbkb* input_activations_V_s_U;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<10> > input_activations_V_s_address0;
    sc_signal< sc_logic > input_activations_V_s_ce0;
    sc_signal< sc_lv<8> > input_activations_V_s_q0;
    sc_signal< sc_logic > image_in_V_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<6> > i_fu_93_p2;
    sc_signal< sc_lv<6> > i_reg_140;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<12> > tmp_141_cast_fu_107_p1;
    sc_signal< sc_lv<12> > tmp_141_cast_reg_145;
    sc_signal< sc_lv<1> > exitcond46_i_i_fu_87_p2;
    sc_signal< sc_lv<6> > j_fu_117_p2;
    sc_signal< sc_lv<6> > j_reg_153;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > exitcond45_i_i_fu_111_p2;
    sc_signal< sc_lv<6> > i_0_i_i_reg_65;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<6> > j_0_i_i_reg_76;
    sc_signal< sc_lv<64> > tmp_142_cast_fu_132_p1;
    sc_signal< sc_lv<11> > tmp_fu_99_p3;
    sc_signal< sc_lv<12> > tmp_i_cast_fu_123_p1;
    sc_signal< sc_lv<12> > tmp_s_fu_127_p2;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_state2;
    static const sc_lv<4> ap_ST_fsm_state3;
    static const sc_lv<4> ap_ST_fsm_state4;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<6> ap_const_lv6_20;
    static const sc_lv<6> ap_const_lv6_1;
    static const sc_lv<5> ap_const_lv5_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_block_state1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_exitcond45_i_i_fu_111_p2();
    void thread_exitcond46_i_i_fu_87_p2();
    void thread_i_fu_93_p2();
    void thread_image_in_V_V_blk_n();
    void thread_image_in_V_V_din();
    void thread_image_in_V_V_write();
    void thread_input_activations_V_s_address0();
    void thread_input_activations_V_s_ce0();
    void thread_j_fu_117_p2();
    void thread_tmp_141_cast_fu_107_p1();
    void thread_tmp_142_cast_fu_132_p1();
    void thread_tmp_fu_99_p3();
    void thread_tmp_i_cast_fu_123_p1();
    void thread_tmp_s_fu_127_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
