// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_nnet (
hls::stream<ap_fixed<32, 4, (ap_q_mode) 3, (ap_o_mode)3, 0> > (&fc3_out));
